import GeometryOfNumbers.Geometry
import GeometryOfNumbers.Analysis.RealDepthMass
import GeometryOfNumbers.Analysis.RealQuadraticAmplitude
import GeometryOfNumbers.Analysis.RealCriticalDepthState
import GeometryOfNumbers.Analysis.QuadraticCenteredBracket
import GeometryOfNumbers.Analysis.CenterLegForm
import GeometryOfNumbers.Analysis.CenterLegCameraForm
import GeometryOfNumbers.Analysis.CenterLegAtlasForm
import GeometryOfNumbers.Analysis.QuadraticCameraBracket
import GeometryOfNumbers.Analysis.OddCameraQuadraticCrosswalk
import GeometryOfNumbers.Analysis.PrimeResidualDepthCrosswalk
import GeometryOfNumbers.Analysis.PrimeCarryVoice

/-! Separate entry point for Zone B. `GeometryOfNumbers` remains discrete only. -/
