import GeometryOfNumbers.Foundation.EmergentCycleTransport

/-!
# A residual tower generated by the same cycle operation

Source: `quantity-representation-foundations`, commit
`66f9ab46c6fa2622c5e6d9f5ed2c497040c62374`, especially
`IteratedEmergentPositionalExpansion.lean`.

At depth zero only the unresolved count remains. Each further level extracts
one residual and applies the same construction to its completed-cycle count.
The carrier is a nested tuple, with the lowest residual first and the tail last.
No division, modulo, numeral expansion, measure, or metric is an input.

Bounds, exact reconstruction, and uniqueness are proved from the one-cell
specification. Powers appear only in a subsequent reconstruction theorem.
The number of possible bounded residual prefixes is not counted in this module.
-/

namespace GeometryOfNumbers.Foundation

set_option autoImplicit false
universe u v

/-- `depth` residual positions followed by one unresolved count. -/
def ResidualTowerCoordinates : Nat → Type
  | 0 => Nat
  | depth + 1 => Nat × ResidualTowerCoordinates depth

/-- The tower is generated by repeated use of the already constructed cycle map. -/
def emergentResidualTower (b : Nat) : (depth : Nat) → Nat → ResidualTowerCoordinates depth
  | 0, n => n
  | depth + 1, n =>
      (cycleResidual b n, emergentResidualTower b depth (completedCycleCount b n))

/-- Reconstruct from the unresolved count, reinserting each extracted residual. -/
def residualTowerValue (b : Nat) : {depth : Nat} → ResidualTowerCoordinates depth → Nat
  | 0, tail => tail
  | _ + 1, (residual, rest) => residualTowerValue b rest * b + residual

/-- Bounds constrain only residual coordinates, never the unresolved tail. -/
def BoundedResidualTower (b : Nat) : {depth : Nat} → ResidualTowerCoordinates depth → Prop
  | 0, _ => True
  | _ + 1, (residual, rest) => residual < b ∧ BoundedResidualTower b rest

/-- Every extracted residual stays below the same capacity. -/
theorem emergentResidualTower_bounded (b depth n : Nat) (hb : 0 < b) :
    BoundedResidualTower b (emergentResidualTower b depth n) := by
  induction depth generalizing n with
  | zero => exact True.intro
  | succ depth ih =>
    exact ⟨(cycleCoordinatesRec_spec b hb n).2, ih (completedCycleCount b n)⟩

/-- The whole tower, including its tail, exactly reconstructs the starting count. -/
theorem emergentResidualTower_value (b depth n : Nat) (hb : 0 < b) :
    residualTowerValue b (emergentResidualTower b depth n) = n := by
  induction depth generalizing n with
  | zero => rfl
  | succ depth ih =>
    change residualTowerValue b (emergentResidualTower b depth (completedCycleCount b n)) * b +
      cycleResidual b n = n
    rw [ih]
    exact (cycleCoordinatesRec_spec b hb n).1.symm

/-- Two bounded towers of equal depth reconstructing the same count must coincide. -/
theorem residualTower_unique (b depth : Nat)
    (left right : ResidualTowerCoordinates depth)
    (hleft : BoundedResidualTower b left) (hright : BoundedResidualTower b right)
    (hvalue : residualTowerValue b left = residualTowerValue b right) : left = right := by
  induction depth with
  | zero => exact hvalue
  | succ depth ih =>
    rcases left with ⟨r, rest⟩
    rcases right with ⟨s, rest'⟩
    have hcoords := cycleDecomposition_unique
      (b := b) (n := residualTowerValue b (depth := depth + 1) (r, rest))
      (c₁ := residualTowerValue b rest) (r₁ := r)
      (c₂ := residualTowerValue b rest') (r₂ := s)
      ⟨rfl, hleft.1⟩ ⟨hvalue, hright.1⟩
    exact Prod.ext hcoords.2 (ih rest rest' hleft.2 hright.2 hcoords.1)

/-- Any bounded tower reconstructing `n` is the canonical iterated tower. -/
theorem residualTower_eq_canonical (b depth n : Nat) (hb : 0 < b)
    (coordinates : ResidualTowerCoordinates depth)
    (hbound : BoundedResidualTower b coordinates)
    (hvalue : residualTowerValue b coordinates = n) :
    coordinates = emergentResidualTower b depth n :=
  residualTower_unique b depth coordinates (emergentResidualTower b depth n)
    hbound (emergentResidualTower_bounded b depth n hb)
    (hvalue.trans (emergentResidualTower_value b depth n hb).symm)

/-- Extract the unresolved count after all residual levels. -/
def residualTowerTail : {depth : Nat} → ResidualTowerCoordinates depth → Nat
  | 0, tail => tail
  | _ + 1, (_, rest) => residualTowerTail rest

/-- Weighted residual contribution, reconstructed with a zero tail. -/
def residualTowerPrefixValue (b : Nat) : {depth : Nat} → ResidualTowerCoordinates depth → Nat
  | 0, _ => 0
  | _ + 1, (residual, rest) => residualTowerPrefixValue b rest * b + residual

private theorem addMul (a c b : Nat) : (a + c) * b = a * b + c * b := by
  rw [Nat.mul_comm (a + c) b, Nat.mul_add, Nat.mul_comm b a, Nat.mul_comm b c]

private theorem mulAssoc (a c b : Nat) : (a * c) * b = a * (c * b) := by
  induction b with
  | zero => rfl
  | succ b ih => rw [Nat.mul_succ, Nat.mul_succ, Nat.mul_add, ih]

/-- Powers arise from repeated reconstruction, not as inputs defining the tower.
The prefix is the recursive sum `r₀ + b*r₁ + ...`; the tail is never discarded. -/
theorem residualTowerValue_eq_prefix_add_scaled_tail (b depth : Nat)
    (coordinates : ResidualTowerCoordinates depth) :
    residualTowerValue b coordinates = residualTowerPrefixValue b coordinates +
      residualTowerTail coordinates * b ^ depth := by
  induction depth with
  | zero =>
    change Nat at coordinates
    change coordinates = 0 + coordinates * b ^ 0
    rw [Nat.pow_zero, Nat.mul_one, Nat.zero_add]
  | succ depth ih =>
    rcases coordinates with ⟨residual, rest⟩
    change residualTowerValue b rest * b + residual =
      (residualTowerPrefixValue b rest * b + residual) +
        residualTowerTail rest * b ^ (depth + 1)
    rw [ih rest, addMul, mulAssoc, Nat.pow_succ,
      Nat.add_right_comm (residualTowerPrefixValue b rest * b)
        (residualTowerTail rest * (b ^ depth * b)) residual]

/-- Exact finite-depth expansion obtained after the tower has been constructed. -/
theorem emergentResidualTower_expansion (b depth n : Nat) (hb : 0 < b) :
    n = residualTowerPrefixValue b (emergentResidualTower b depth n) +
      residualTowerTail (emergentResidualTower b depth n) * b ^ depth :=
  (emergentResidualTower_value b depth n hb).symm.trans
    (residualTowerValue_eq_prefix_add_scaled_tail b depth _)

/-- Forget higher residual detail by reconstructing it into the lower tower's
tail. `extra + depth` makes the recursive type alignment definitional. -/
def truncateResidualTower (b : Nat) : (depth extra : Nat) →
    ResidualTowerCoordinates (extra + depth) → ResidualTowerCoordinates depth
  | 0, _, upper => residualTowerValue b upper
  | depth + 1, extra, (residual, rest) =>
      (residual, truncateResidualTower b depth extra rest)

/-- Building deeper and then truncating gives exactly the original lower tower. -/
theorem emergentResidualTower_truncate (b depth extra n : Nat) (hb : 0 < b) :
    truncateResidualTower b depth extra (emergentResidualTower b (extra + depth) n) =
      emergentResidualTower b depth n := by
  induction depth generalizing n with
  | zero => exact emergentResidualTower_value b extra n hb
  | succ depth ih =>
    exact Prod.ext rfl (ih (completedCycleCount b n))

/-- At the first level the tower keeps the original local observation. Upper
levels operate on the constructed cycle counts, not on an arbitrary extension. -/
theorem emergentResidualTower_first_residual_preserves_observation
    {Q : Type u} {Local : Type v} (trajectory : UnitTrajectory Q)
    (model : AutonomousLocalDynamics trajectory Local) {b : Nat}
    (hcapacity : EmergentLocalCapacity trajectory model b) (depth n : Nat) :
    model.observe (trajectory.state n) = model.observe
      (trajectory.state (emergentResidualTower b (depth + 1) n).1) :=
  cycleResidual_controls_localReadout trajectory model hcapacity n

end GeometryOfNumbers.Foundation
