import GeometryOfNumbers.Foundation.FirstLocalReturnCapacity

/-!
# First return to lossless cycle/reset coordinates

Constructive ports of `EmergentCycleDecomposition.lean` and
`EmergentQuotientRemainder.lean` from `quantity-representation-foundations`,
commit `66f9ab46c6fa2622c5e6d9f5ed2c497040c62374`.

The external unit clock is decomposed by recursion, without division, modulo,
digits, or a positional tower. The specification and uniqueness prove that
reset increments exactly one complete-cycle unit while preserving the count.
For the dynamically emergent capacity, the residual controls the original
local observation. A faithful extension must distinguish the reset endpoints.
-/

namespace GeometryOfNumbers.Foundation

set_option autoImplicit false
universe u v w

/-- A bounded residual and complete-cycle count reconstruct the external clock. -/
def IsCycleDecomposition (b n cycles residual : Nat) : Prop :=
  n = cycles * b + residual ∧ residual < b

/-- One unit step either advances inside the cycle or records a completed cycle. -/
def nextCycleCoordinates (b : Nat) (coordinates : Nat × Nat) : Nat × Nat :=
  if coordinates.2 + 1 < b then
    (coordinates.1, coordinates.2 + 1)
  else
    (coordinates.1 + 1, 0)

/-- Computable cycle coordinates; no Euclidean quotient or remainder is used. -/
def cycleCoordinatesRec (b : Nat) : Nat → Nat × Nat
  | 0 => (0, 0)
  | n + 1 => nextCycleCoordinates b (cycleCoordinatesRec b n)

/-- Number of full cycles generated by unit stepping. -/
def completedCycleCount (b n : Nat) : Nat := (cycleCoordinatesRec b n).1

/-- Position inside the cycle generated by unit stepping. -/
def cycleResidual (b n : Nat) : Nat := (cycleCoordinatesRec b n).2

private theorem reachesBoundary {residual b : Nat}
    (hr : residual < b) (hnext : ¬ residual + 1 < b) : residual + 1 = b :=
  Nat.le_antisymm (Nat.succ_le_of_lt hr) (Nat.le_of_not_gt hnext)

/-- Every recursive update conserves the external count and bounds the residual. -/
theorem cycleCoordinatesRec_spec (b : Nat) (hb : 0 < b) (n : Nat) :
    IsCycleDecomposition b n (completedCycleCount b n) (cycleResidual b n) := by
  unfold completedCycleCount cycleResidual
  induction n with
  | zero =>
    change 0 = 0 * b + 0 ∧ 0 < b
    exact ⟨(Nat.zero_mul b).symm, hb⟩
  | succ n ih =>
    rcases ih with ⟨hvalue, hr⟩
    change (n + 1 = (nextCycleCoordinates b (cycleCoordinatesRec b n)).1 * b +
      (nextCycleCoordinates b (cycleCoordinatesRec b n)).2) ∧
      (nextCycleCoordinates b (cycleCoordinatesRec b n)).2 < b
    unfold nextCycleCoordinates
    by_cases hnext : (cycleCoordinatesRec b n).2 + 1 < b
    · rw [if_pos hnext]
      exact ⟨(congrArg (fun x => x + 1) hvalue).trans
        (Nat.add_assoc _ _ _), hnext⟩
    · rw [if_neg hnext]
      have hboundary := reachesBoundary hr hnext
      constructor
      · calc
          n + 1 = ((cycleCoordinatesRec b n).1 * b +
              (cycleCoordinatesRec b n).2) + 1 := congrArg (fun x => x + 1) hvalue
          _ = (cycleCoordinatesRec b n).1 * b +
              ((cycleCoordinatesRec b n).2 + 1) := Nat.add_assoc _ _ _
          _ = (cycleCoordinatesRec b n).1 * b + b :=
            congrArg (fun x => (cycleCoordinatesRec b n).1 * b + x) hboundary
          _ = ((cycleCoordinatesRec b n).1 + 1) * b + 0 :=
            (Nat.succ_mul _ _).symm.trans (Nat.add_zero _).symm
      · exact hb

private theorem cancelAddLeft (a x y : Nat) (h : a + x = a + y) : x = y := by
  induction a with
  | zero => rw [Nat.zero_add, Nat.zero_add] at h; exact h
  | succ a ih =>
    rw [Nat.succ_add, Nat.succ_add] at h
    exact ih (Nat.succ.inj h)

private theorem beforeNextBoundary {b cycles residual : Nat} (hr : residual < b) :
    cycles * b + residual < (cycles + 1) * b := by
  rw [Nat.succ_mul]
  exact Nat.add_lt_add_left hr _

/-- Bounded, count-preserving cycle coordinates are unique, before any QR API. -/
theorem cycleDecomposition_unique {b n c₁ r₁ c₂ r₂ : Nat}
    (h₁ : IsCycleDecomposition b n c₁ r₁)
    (h₂ : IsCycleDecomposition b n c₂ r₂) : c₁ = c₂ ∧ r₁ = r₂ := by
  have heq : c₁ * b + r₁ = c₂ * b + r₂ := h₁.1.symm.trans h₂.1
  have orderedImpossible {c r d t : Nat} (hr : r < b)
      (h : c * b + r = d * b + t) : ¬ c < d := by
    intro hcd
    have hlt : c * b + r < d * b + t :=
      Nat.lt_of_lt_of_le (beforeNextBoundary hr)
        (Nat.le_trans (Nat.mul_le_mul_right b (Nat.succ_le_of_lt hcd))
          (Nat.le_add_right _ _))
    exact Nat.ne_of_lt hlt h
  have hc : c₁ = c₂ := Nat.le_antisymm
    (Nat.le_of_not_gt (orderedImpossible h₂.2 heq.symm))
    (Nat.le_of_not_gt (orderedImpossible h₁.2 heq))
  refine ⟨hc, ?_⟩
  rw [hc] at heq
  exact cancelAddLeft _ _ _ heq

/-- The recursive construction is the unique bounded normalization of the count. -/
theorem cycleDecomposition_eq_recursive {b n cycles residual : Nat} (hb : 0 < b)
    (h : IsCycleDecomposition b n cycles residual) :
    cycles = completedCycleCount b n ∧ residual = cycleResidual b n :=
  cycleDecomposition_unique h (cycleCoordinatesRec_spec b hb n)

/-- Below saturation, only the residual advances. -/
theorem cycle_step_inside {b n : Nat} (hnext : cycleResidual b n + 1 < b) :
    completedCycleCount b (n + 1) = completedCycleCount b n ∧
      cycleResidual b (n + 1) = cycleResidual b n + 1 := by
  unfold cycleResidual at hnext
  change (nextCycleCoordinates b (cycleCoordinatesRec b n)).1 =
      (cycleCoordinatesRec b n).1 ∧
    (nextCycleCoordinates b (cycleCoordinatesRec b n)).2 =
      (cycleCoordinatesRec b n).2 + 1
  unfold nextCycleCoordinates
  rw [if_pos hnext]
  exact ⟨rfl, rfl⟩

/-- Saturation resets the residual and transfers exactly one completed-cycle unit. -/
theorem cycle_step_at_boundary {b n : Nat} (hboundary : cycleResidual b n + 1 = b) :
    completedCycleCount b (n + 1) = completedCycleCount b n + 1 ∧
      cycleResidual b (n + 1) = 0 := by
  unfold cycleResidual at hboundary
  have hnot : ¬ (cycleCoordinatesRec b n).2 + 1 < b := by
    intro hlt
    rw [hboundary] at hlt
    exact Nat.lt_irrefl b hlt
  change (nextCycleCoordinates b (cycleCoordinatesRec b n)).1 =
      (cycleCoordinatesRec b n).1 + 1 ∧
    (nextCycleCoordinates b (cycleCoordinatesRec b n)).2 = 0
  unfold nextCycleCoordinates
  rw [if_neg hnot]
  exact ⟨rfl, rfl⟩

/-- These are the only two regimes along a valid positive-capacity trajectory. -/
theorem cycle_step_dichotomy (b n : Nat) (hb : 0 < b) :
    (cycleResidual b n + 1 < b ∧
      completedCycleCount b (n + 1) = completedCycleCount b n ∧
      cycleResidual b (n + 1) = cycleResidual b n + 1) ∨
    (cycleResidual b n + 1 = b ∧
      completedCycleCount b (n + 1) = completedCycleCount b n + 1 ∧
      cycleResidual b (n + 1) = 0) := by
  by_cases hnext : cycleResidual b n + 1 < b
  · exact Or.inl ⟨hnext, cycle_step_inside hnext⟩
  · have hboundary := reachesBoundary (cycleCoordinatesRec_spec b hb n).2 hnext
    exact Or.inr ⟨hboundary, cycle_step_at_boundary hboundary⟩

/-- At the first saturation the canonical coordinates are one complete cycle
and no residual. This is proved by uniqueness, not imposed as an initial value. -/
theorem firstSaturation_coordinates (b : Nat) (hb : 0 < b) :
    completedCycleCount b b = 1 ∧ cycleResidual b b = 0 := by
  have h : IsCycleDecomposition b b 1 0 :=
    ⟨((Nat.one_mul b).trans (Nat.add_zero b)).symm, hb⟩
  have hcoords := cycleDecomposition_eq_recursive hb h
  exact ⟨hcoords.1.symm, hcoords.2.symm⟩

/-- The recursively computed residual preserves the same local readout. -/
theorem cycleResidual_controls_localReadout
    {Q : Type u} {Local : Type v} (trajectory : UnitTrajectory Q)
    (model : AutonomousLocalDynamics trajectory Local) {b : Nat}
    (hcapacity : EmergentLocalCapacity trajectory model b) (n : Nat) :
    model.observe (trajectory.state n) =
      model.observe (trajectory.state (cycleResidual b n)) := by
  have period := positiveLocalReturn_implies_periodic_readout trajectory model hcapacity.1
  have reduce : ∀ cycles residual,
      model.observe (trajectory.state (cycles * b + residual)) =
        model.observe (trajectory.state residual) := by
    intro cycles residual
    induction cycles with
    | zero => rw [Nat.zero_mul, Nat.zero_add]
    | succ cycles ih =>
      rw [Nat.succ_mul, Nat.add_right_comm (cycles * b) b residual, period]
      exact ih
  calc
    model.observe (trajectory.state n) = model.observe (trajectory.state
        (completedCycleCount b n * b + cycleResidual b n)) :=
      congrArg (fun k => model.observe (trajectory.state k))
        (cycleCoordinatesRec_spec b hcapacity.1.1 n).1
    _ = model.observe (trajectory.state (cycleResidual b n)) := reduce _ _

/-- Minimality identifies residual zero with an actual return to the initial
local observation. The recursive reset is therefore not just a label. -/
theorem localReturn_iff_cycleResidual_zero
    {Q : Type u} {Local : Type v} (trajectory : UnitTrajectory Q)
    (model : AutonomousLocalDynamics trajectory Local) {b : Nat}
    (hcapacity : EmergentLocalCapacity trajectory model b) (n : Nat) :
    model.observe (trajectory.state n) = model.observe (trajectory.state 0) ↔
      cycleResidual b n = 0 := by
  have hreadout := cycleResidual_controls_localReadout trajectory model hcapacity n
  constructor
  · intro hreturn
    by_cases hz : cycleResidual b n = 0
    · exact hz
    · have hpos : 0 < cycleResidual b n :=
        Nat.lt_of_le_of_ne (Nat.zero_le _) (fun h => hz h.symm)
      have hleast : b ≤ cycleResidual b n :=
        hcapacity.2 _ ⟨hpos, hreadout.symm.trans hreturn⟩
      exact False.elim (Nat.not_lt_of_ge hleast (cycleCoordinatesRec_spec b hcapacity.1.1 n).2)
  · intro hz
    exact hreadout.trans (congrArg (fun r => model.observe (trajectory.state r)) hz)

/-- Reset cannot erase quantity information: a faithful extension distinguishes
the two endpoints even though the local channel repeats. -/
theorem cycle_reset_forces_extension_difference
    {Q : Type u} {Local : Type v} {Extension : Type w}
    (trajectory : UnitTrajectory Q) (model : AutonomousLocalDynamics trajectory Local)
    (encode : Q → Local × Extension) (hfaithful : FaithfulRepresentation encode)
    (hagrees : ∀ x, (encode x).1 = model.observe x) {b : Nat}
    (hcapacity : EmergentLocalCapacity trajectory model b) (n : Nat) :
    (encode (trajectory.state n)).2 ≠ (encode (trajectory.state (n + b))).2 := by
  apply localRecurrence_forces_extension_difference trajectory encode hfaithful
  constructor
  · have hlt := Nat.add_lt_add_left hcapacity.1.1 n
    rw [Nat.add_zero] at hlt
    exact hlt
  · change (encode (trajectory.state n)).1 = (encode (trajectory.state (n + b))).1
    rw [hagrees, hagrees]
    exact (positiveLocalReturn_implies_periodic_readout trajectory model hcapacity.1 n).symm

end GeometryOfNumbers.Foundation
