import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms BaseTwoCenterL2
#print axioms BaseTwoCenterL2
#assert_analysis_axioms baseTwoCenterGapNorm
#print axioms baseTwoCenterGapNorm
#assert_analysis_axioms baseTwoCenterLogGap_right_pos
#print axioms baseTwoCenterLogGap_right_pos
#assert_analysis_axioms baseTwoCenterGapNorm_pos
#print axioms baseTwoCenterGapNorm_pos
#assert_analysis_axioms baseTwoCenterGapNorm_sq
#print axioms baseTwoCenterGapNorm_sq
#assert_analysis_axioms baseTwoCenterLegUnit
#print axioms baseTwoCenterLegUnit
#assert_analysis_axioms baseTwoCenterLegUnit_sum_sq
#print axioms baseTwoCenterLegUnit_sum_sq
#assert_analysis_axioms baseTwoCenterLegSynthesis
#print axioms baseTwoCenterLegSynthesis
#assert_analysis_axioms baseTwoCenterLegSynthesis_apply
#print axioms baseTwoCenterLegSynthesis_apply
#assert_analysis_axioms baseTwoCenterLegSynthesis_norm
#print axioms baseTwoCenterLegSynthesis_norm
#assert_analysis_axioms baseTwoNormalizedCenterReconstructionRaw
#print axioms baseTwoNormalizedCenterReconstructionRaw
#assert_analysis_axioms baseTwoCenterCoupling_normalized_coordinate
#print axioms baseTwoCenterCoupling_normalized_coordinate
#assert_analysis_axioms baseTwoNormalizedCenterReconstructionRaw_summable_sq
#print axioms baseTwoNormalizedCenterReconstructionRaw_summable_sq
#assert_analysis_axioms baseTwoNormalizedCenterReconstructionRaw_energy
#print axioms baseTwoNormalizedCenterReconstructionRaw_energy
#assert_analysis_axioms baseTwoNormalizedCenterReconstructionRaw_memℓp
#print axioms baseTwoNormalizedCenterReconstructionRaw_memℓp
#assert_analysis_axioms baseTwoNormalizedCenterReconstruction
#print axioms baseTwoNormalizedCenterReconstruction
#assert_analysis_axioms baseTwoNormalizedCenterReconstruction_apply
#print axioms baseTwoNormalizedCenterReconstruction_apply
#assert_analysis_axioms baseTwoNormalizedCenterReconstruction_norm
#print axioms baseTwoNormalizedCenterReconstruction_norm
#assert_analysis_axioms baseTwoNormalizedCenterReconstruction_norm_le
#print axioms baseTwoNormalizedCenterReconstruction_norm_le
#assert_analysis_axioms baseTwoCenterCoupling_factorization
#print axioms baseTwoCenterCoupling_factorization
#assert_analysis_axioms baseTwoNormalizedCenterReconstruction_concrete
#print axioms baseTwoNormalizedCenterReconstruction_concrete
end GeometryOfNumbers.Analysis.BaseTwoCompletion
