import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoPhysicalOddEndpointLog
#print axioms baseTwoPhysicalOddEndpointLog
#assert_analysis_axioms baseTwoPhysicalEndpointClock
#print axioms baseTwoPhysicalEndpointClock
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect
#print axioms baseTwoPhysicalCenterClockDefect
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_left
#print axioms baseTwoPhysicalCenterClockDefect_left
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_right
#print axioms baseTwoPhysicalCenterClockDefect_right
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_decoded_center
#print axioms baseTwoPhysicalCenterClockDefect_decoded_center
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_norm_le
#print axioms baseTwoPhysicalCenterClockDefect_norm_le
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_memℓp
#print axioms baseTwoPhysicalCenterClockDefect_memℓp
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectL2
#print axioms baseTwoPhysicalCenterClockDefectL2
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectL2_apply
#print axioms baseTwoPhysicalCenterClockDefectL2_apply
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectC2State
#print axioms baseTwoPhysicalCenterClockDefectC2State
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectC2State_apply
#print axioms baseTwoPhysicalCenterClockDefectC2State_apply
end GeometryOfNumbers.Analysis.BaseTwoCompletion
