import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectPreStencil
#print axioms baseTwoPhysicalCenterClockDefectPreStencil
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectPreStencil_components
#print axioms baseTwoPhysicalCenterClockDefectPreStencil_components
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectGreenState_seed_zero
#print axioms baseTwoPhysicalCenterClockDefectGreenState_seed_zero
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectGreenState_three_ne_zero
#print axioms baseTwoPhysicalCenterClockDefectGreenState_three_ne_zero
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectGreenState_ne_zero
#print axioms baseTwoPhysicalCenterClockDefectGreenState_ne_zero
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_seedResidual_ne_zero
#print axioms baseTwoPhysicalCenterClockDefect_seedResidual_ne_zero
#assert_analysis_axioms baseTwoPhysicalCenterClockDefect_directGreen_ne_zero
#print axioms baseTwoPhysicalCenterClockDefect_directGreen_ne_zero
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectPreStencil_both_sectors
#print axioms baseTwoPhysicalCenterClockDefectPreStencil_both_sectors
end GeometryOfNumbers.Analysis.BaseTwoCompletion
