import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling
#print axioms baseTwoPhysicalCenterSelfCoupling
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_apply
#print axioms baseTwoPhysicalCenterSelfCoupling_apply
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_first_cell
#print axioms baseTwoPhysicalCenterSelfCoupling_first_cell
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_inner_left_right
#print axioms baseTwoPhysicalCenterSelfCoupling_inner_left_right
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_inner_right_image
#print axioms baseTwoPhysicalCenterSelfCoupling_inner_right_image
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_not_symmetric
#print axioms baseTwoPhysicalCenterSelfCoupling_not_symmetric
end GeometryOfNumbers.Analysis.BaseTwoCompletion
