import GeometryOfNumbers.Analysis.BaseTwoRawL2ReadoutObstruction
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms MaterialEdgeL2
#print axioms MaterialEdgeL2
#assert_analysis_axioms baseTwoSignedEdge
#print axioms baseTwoSignedEdge
#assert_analysis_axioms baseTwoSignedEdge_injective
#print axioms baseTwoSignedEdge_injective
#assert_analysis_axioms baseTwoRawEdgeCoefficient
#print axioms baseTwoRawEdgeCoefficient
#assert_analysis_axioms baseTwoRawEdgeCoefficient_signedEdge
#print axioms baseTwoRawEdgeCoefficient_signedEdge
#assert_analysis_axioms baseTwoCompletedUndressedReadout_single
#print axioms baseTwoCompletedUndressedReadout_single
#assert_analysis_axioms baseTwoRawL2Witness
#print axioms baseTwoRawL2Witness
#assert_analysis_axioms baseTwoRawL2Witness_apply
#print axioms baseTwoRawL2Witness_apply
#assert_analysis_axioms baseTwoRawL2Witness_signedEdge
#print axioms baseTwoRawL2Witness_signedEdge
#assert_analysis_axioms baseTwoRawL2Witness_norm_sq
#print axioms baseTwoRawL2Witness_norm_sq
#assert_analysis_axioms baseTwoRawL2Witness_norm
#print axioms baseTwoRawL2Witness_norm
#assert_analysis_axioms baseTwoRawL2Witness_readout
#print axioms baseTwoRawL2Witness_readout
#assert_analysis_axioms baseTwoRawL2Readout_not_exists
#print axioms baseTwoRawL2Readout_not_exists
#assert_analysis_axioms baseTwoCompletedReadout_no_rawL2_extension
#print axioms baseTwoCompletedReadout_no_rawL2_extension
#assert_analysis_axioms baseTwoRawL2_no_bounded_boundary_factorization
#print axioms baseTwoRawL2_no_bounded_boundary_factorization
end GeometryOfNumbers.Analysis.BaseTwoCompletion
