import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoSampledHardy_tail
#print axioms baseTwoSampledHardy_tail
#assert_analysis_axioms baseTwoSampledHardy_finite
#print axioms baseTwoSampledHardy_finite
end GeometryOfNumbers.Analysis.BaseTwoCompletion
