import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoCenterCoupling_seed_finite
#print axioms baseTwoCenterCoupling_seed_finite
#assert_analysis_axioms baseTwoCenterCoupling_seed_tsum
#print axioms baseTwoCenterCoupling_seed_tsum
#assert_analysis_axioms baseTwoCenterLogGap_bound
#print axioms baseTwoCenterLogGap_bound
#assert_analysis_axioms baseTwoCenterCouplingRaw_finite_bound
#print axioms baseTwoCenterCouplingRaw_finite_bound
#assert_analysis_axioms baseTwoCenterCouplingRaw_summable_sq
#print axioms baseTwoCenterCouplingRaw_summable_sq
#assert_analysis_axioms baseTwoCenterCouplingRaw_memℓp
#print axioms baseTwoCenterCouplingRaw_memℓp
#assert_analysis_axioms baseTwoCenterCouplingL2
#print axioms baseTwoCenterCouplingL2
#assert_analysis_axioms baseTwoCenterCouplingL2_apply
#print axioms baseTwoCenterCouplingL2_apply
#assert_analysis_axioms baseTwoCenterCouplingL2_norm_le
#print axioms baseTwoCenterCouplingL2_norm_le
#assert_analysis_axioms baseTwoCenterCouplingOperator
#print axioms baseTwoCenterCouplingOperator
#assert_analysis_axioms baseTwoCenterCouplingOperator_apply
#print axioms baseTwoCenterCouplingOperator_apply
#assert_analysis_axioms baseTwoCenterCouplingOperator_norm_le
#print axioms baseTwoCenterCouplingOperator_norm_le
#assert_analysis_axioms baseTwoCenterCouplingOperator_concrete
#print axioms baseTwoCenterCouplingOperator_concrete
end GeometryOfNumbers.Analysis.BaseTwoCompletion
