import GeometryOfNumbers.Analysis.BaseTwoCompletedBoundaryLimit
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoCompletedBoundaryPrefix
#print axioms baseTwoCompletedBoundaryPrefix
#assert_analysis_axioms baseTwoCompletedBoundaryValue
#print axioms baseTwoCompletedBoundaryValue
#assert_analysis_axioms baseTwoCompletedBoundaryPrefix_eq_head_sub_seed
#print axioms baseTwoCompletedBoundaryPrefix_eq_head_sub_seed
#assert_analysis_axioms baseTwoCompletedBoundaryPrefix_tendsto
#print axioms baseTwoCompletedBoundaryPrefix_tendsto
#assert_analysis_axioms baseTwoCompletedBoundaryValue_eq_readout_sub_seed
#print axioms baseTwoCompletedBoundaryValue_eq_readout_sub_seed
#assert_analysis_axioms baseTwoCompletedBoundaryValue_add_seed_eq_signal
#print axioms baseTwoCompletedBoundaryValue_add_seed_eq_signal
#assert_analysis_axioms baseTwoCompletedMaterialInteriorPrefix
#print axioms baseTwoCompletedMaterialInteriorPrefix
#assert_analysis_axioms baseTwoCompletedMaterialInteriorPrefix_tendsto
#print axioms baseTwoCompletedMaterialInteriorPrefix_tendsto
end GeometryOfNumbers.Analysis.BaseTwoCompletion
