import GeometryOfNumbers.Analysis.BaseTwoCompletedGradientSignalLift
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms criticalMaterialGradient
#print axioms criticalMaterialGradient
#assert_analysis_axioms criticalMaterialGradient_eq_nativeLinePowerDifference
#print axioms criticalMaterialGradient_eq_nativeLinePowerDifference
#assert_analysis_axioms criticalMaterialGradient_norm_le
#print axioms criticalMaterialGradient_norm_le
#assert_analysis_axioms summable_norm_criticalMaterialGradient
#print axioms summable_norm_criticalMaterialGradient
#assert_analysis_axioms MaterialGradientL1
#print axioms MaterialGradientL1
#assert_analysis_axioms baseTwoCompletedMaterialGradient
#print axioms baseTwoCompletedMaterialGradient
#assert_analysis_axioms baseTwoCompletedMaterialGradient_apply
#print axioms baseTwoCompletedMaterialGradient_apply
#assert_analysis_axioms baseTwoCompletedMaterialGradientL2
#print axioms baseTwoCompletedMaterialGradientL2
#assert_analysis_axioms baseTwoCompletedMaterialGradientL2_apply
#print axioms baseTwoCompletedMaterialGradientL2_apply
#assert_analysis_axioms criticalMaterialSample_eq_seed_add_gradientPrefix
#print axioms criticalMaterialSample_eq_seed_add_gradientPrefix
#assert_analysis_axioms BaseTwoSeededGradientCarrier
#print axioms BaseTwoSeededGradientCarrier
#assert_analysis_axioms baseTwoCompletedUndressedState
#print axioms baseTwoCompletedUndressedState
#assert_analysis_axioms baseTwoCompletedUndressedState_recover
#print axioms baseTwoCompletedUndressedState_recover
#assert_analysis_axioms baseTwoCellLeftEdge
#print axioms baseTwoCellLeftEdge
#assert_analysis_axioms baseTwoCellRightEdge
#print axioms baseTwoCellRightEdge
#assert_analysis_axioms baseTwoCellLeftEdge_eq
#print axioms baseTwoCellLeftEdge_eq
#assert_analysis_axioms baseTwoCellRightEdge_eq
#print axioms baseTwoCellRightEdge_eq
#assert_analysis_axioms baseTwoCriticalCenterCell_eq_gradientEdges
#print axioms baseTwoCriticalCenterCell_eq_gradientEdges
#assert_analysis_axioms baseTwoCompletedUndressedReadout
#print axioms baseTwoCompletedUndressedReadout
#assert_analysis_axioms baseTwoCompletedUndressedReadout_apply
#print axioms baseTwoCompletedUndressedReadout_apply
#assert_analysis_axioms baseTwoCompletedUndressedReadout_eq_signal
#print axioms baseTwoCompletedUndressedReadout_eq_signal
#assert_analysis_axioms baseTwoCompletedUndressedReadout_dressed_eq_response
#print axioms baseTwoCompletedUndressedReadout_dressed_eq_response
end GeometryOfNumbers.Analysis.BaseTwoCompletion
