import GeometryOfNumbers.Analysis.BaseTwoCompletedSignalRegularity
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion

#assert_base_two_completion_axioms baseTwoComplexMaterialExponent
#print axioms baseTwoComplexMaterialExponent
#assert_base_two_completion_axioms baseTwoComplexCenterCell
#print axioms baseTwoComplexCenterCell
#assert_base_two_completion_axioms baseTwoComplexCompleteSignal
#print axioms baseTwoComplexCompleteSignal
#assert_base_two_completion_axioms baseTwoComplexCenterCell_ofReal
#print axioms baseTwoComplexCenterCell_ofReal
#assert_base_two_completion_axioms baseTwoComplexCompleteSignal_ofReal
#print axioms baseTwoComplexCompleteSignal_ofReal
#assert_base_two_completion_axioms baseTwoComplexCenterCell_norm_le
#print axioms baseTwoComplexCenterCell_norm_le
#assert_base_two_completion_axioms baseTwoComplexCompleteSignal_differentiableOn_ball
#print axioms baseTwoComplexCompleteSignal_differentiableOn_ball
#assert_base_two_completion_axioms baseTwoCriticalCompleteSignal_contDiff
#print axioms baseTwoCriticalCompleteSignal_contDiff
#assert_base_two_completion_axioms baseTwoCriticalCompleteSignal_analyticAt
#print axioms baseTwoCriticalCompleteSignal_analyticAt
#assert_base_two_completion_axioms baseTwoFiniteHead_contDiff
#print axioms baseTwoFiniteHead_contDiff
#assert_base_two_completion_axioms baseTwoCriticalCompleteTail_contDiff
#print axioms baseTwoCriticalCompleteTail_contDiff
#assert_base_two_completion_axioms baseTwoSynthesizedTailCoefficient_eq_normalizedTailJet
#print axioms baseTwoSynthesizedTailCoefficient_eq_normalizedTailJet

end GeometryOfNumbers.Analysis.BaseTwoCompletion
