import GeometryOfNumbers.Analysis.BaseTwoSynthesizedClockMoments
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion

#assert_base_two_completion_axioms baseTwoClosedResponseSeries
#print axioms baseTwoClosedResponseSeries
#assert_base_two_completion_axioms baseTwoSynthesizedResponseSeries
#print axioms baseTwoSynthesizedResponseSeries
#assert_base_two_completion_axioms baseTwoClosedResponseSeries_eq_synthesized
#print axioms baseTwoClosedResponseSeries_eq_synthesized
#assert_base_two_completion_axioms baseTwoClosedResponseSeries_cutoff_independent
#print axioms baseTwoClosedResponseSeries_cutoff_independent
#assert_base_two_completion_axioms baseTwoClosedResponseSeries_camera_quotient
#print axioms baseTwoClosedResponseSeries_camera_quotient
#assert_base_two_completion_axioms baseTwoHistoricalPhi
#print axioms baseTwoHistoricalPhi
#assert_base_two_completion_axioms baseTwoSynthesizedPhi
#print axioms baseTwoSynthesizedPhi
#assert_base_two_completion_axioms baseTwoHistoricalPhi_eq_synthesized
#print axioms baseTwoHistoricalPhi_eq_synthesized
#assert_base_two_completion_axioms baseTwoHistoricalPhi_cutoff_independent
#print axioms baseTwoHistoricalPhi_cutoff_independent
#assert_base_two_completion_axioms baseTwoSynthesizedPhi_coefficient_formula
#print axioms baseTwoSynthesizedPhi_coefficient_formula
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment
#print axioms baseTwoSynthesizedLogMoment
#assert_base_two_completion_axioms baseTwoHistoricalLogMoment
#print axioms baseTwoHistoricalLogMoment
#assert_base_two_completion_axioms baseTwoHistoricalLogMoment_eq_synthesized
#print axioms baseTwoHistoricalLogMoment_eq_synthesized
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_cutoff_independent
#print axioms baseTwoSynthesizedLogMoment_cutoff_independent
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_isSequence
#print axioms baseTwoSynthesizedLogMoment_isSequence
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_unique
#print axioms baseTwoSynthesizedLogMoment_unique
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_formal_logDerivative
#print axioms baseTwoSynthesizedLogMoment_formal_logDerivative
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_formal_quotient
#print axioms baseTwoSynthesizedLogMoment_formal_quotient
#assert_base_two_completion_axioms baseTwoLogMoment_relation_of_formal_identity
#print axioms baseTwoLogMoment_relation_of_formal_identity
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_unique_of_formal_identity
#print axioms baseTwoSynthesizedLogMoment_unique_of_formal_identity
#assert_base_two_completion_axioms baseTwoLogMoment_two_formal_constructions_eq
#print axioms baseTwoLogMoment_two_formal_constructions_eq
#assert_base_two_completion_axioms baseTwoSynthesizedLogMoment_depends_only_on_phi
#print axioms baseTwoSynthesizedLogMoment_depends_only_on_phi

end GeometryOfNumbers.Analysis.BaseTwoCompletion
