import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoPhysicalOddEndpointDiagonalClock
#print axioms baseTwoPhysicalOddEndpointDiagonalClock
#assert_analysis_axioms baseTwoPhysicalOddEndpointDiagonalClock_apply
#print axioms baseTwoPhysicalOddEndpointDiagonalClock_apply
#assert_analysis_axioms baseTwoPhysicalClock_C2_decomposition
#print axioms baseTwoPhysicalClock_C2_decomposition
#assert_analysis_axioms baseTwoPhysicalC2GreenIsometry
#print axioms baseTwoPhysicalC2GreenIsometry
#assert_analysis_axioms baseTwoPhysicalC2GreenIsometry_apply
#print axioms baseTwoPhysicalC2GreenIsometry_apply
#assert_analysis_axioms baseTwoPhysicalC2GreenIsometry_off_sector
#print axioms baseTwoPhysicalC2GreenIsometry_off_sector
#assert_analysis_axioms baseTwoPhysicalC2GreenIsometry_norm
#print axioms baseTwoPhysicalC2GreenIsometry_norm
#assert_analysis_axioms baseTwoPhysicalOrdinaryGreenState
#print axioms baseTwoPhysicalOrdinaryGreenState
#assert_analysis_axioms baseTwoPhysicalLogGradientGreenState
#print axioms baseTwoPhysicalLogGradientGreenState
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectGreenState
#print axioms baseTwoPhysicalCenterClockDefectGreenState
#assert_analysis_axioms baseTwoPhysicalOddEndpointClockGreenState
#print axioms baseTwoPhysicalOddEndpointClockGreenState
#assert_analysis_axioms baseTwoPhysicalOrdinaryGreenState_apply
#print axioms baseTwoPhysicalOrdinaryGreenState_apply
#assert_analysis_axioms baseTwoPhysicalLogGradientGreenState_apply
#print axioms baseTwoPhysicalLogGradientGreenState_apply
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectGreenState_apply
#print axioms baseTwoPhysicalCenterClockDefectGreenState_apply
#assert_analysis_axioms baseTwoPhysicalOddEndpointClockGreenState_apply
#print axioms baseTwoPhysicalOddEndpointClockGreenState_apply
#assert_analysis_axioms baseTwoPhysicalClock_Green_decomposition
#print axioms baseTwoPhysicalClock_Green_decomposition
#assert_analysis_axioms baseTwoPhysicalOrdinaryGreenState_mem_domain
#print axioms baseTwoPhysicalOrdinaryGreenState_mem_domain
#assert_analysis_axioms baseTwoPhysicalMaterialLogGenerator_eq_endpoint
#print axioms baseTwoPhysicalMaterialLogGenerator_eq_endpoint
#assert_analysis_axioms baseTwoPhysicalClock_Green_generator_decomposition
#print axioms baseTwoPhysicalClock_Green_generator_decomposition
#assert_analysis_axioms baseTwoPhysicalOrdinaryParsevalState
#print axioms baseTwoPhysicalOrdinaryParsevalState
#assert_analysis_axioms baseTwoPhysicalLogGradientParsevalState
#print axioms baseTwoPhysicalLogGradientParsevalState
#assert_analysis_axioms baseTwoPhysicalCenterClockDefectParsevalState
#print axioms baseTwoPhysicalCenterClockDefectParsevalState
#assert_analysis_axioms baseTwoPhysicalOrdinaryParsevalState_mem_domain
#print axioms baseTwoPhysicalOrdinaryParsevalState_mem_domain
#assert_analysis_axioms baseTwoPhysicalClock_Parseval_decomposition
#print axioms baseTwoPhysicalClock_Parseval_decomposition
#assert_analysis_axioms baseTwoCenterSample_eq_seed_physical_residual_prefix
#print axioms baseTwoCenterSample_eq_seed_physical_residual_prefix
end GeometryOfNumbers.Analysis.BaseTwoCompletion
