import GeometryOfNumbers.Analysis.BaseTwoSynthesizedClockCompletion
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion

#assert_base_two_completion_axioms baseTwoSynthesizedSignal
#print axioms baseTwoSynthesizedSignal
#assert_base_two_completion_axioms baseTwoSynthesizedSignal_eq_complete
#print axioms baseTwoSynthesizedSignal_eq_complete
#assert_base_two_completion_axioms baseTwoCompletedClockCoefficient
#print axioms baseTwoCompletedClockCoefficient
#assert_base_two_completion_axioms baseTwoSynthesizedClockCoefficient
#print axioms baseTwoSynthesizedClockCoefficient
#assert_base_two_completion_axioms baseTwoSynthesizedSignal_iteratedDeriv
#print axioms baseTwoSynthesizedSignal_iteratedDeriv
#assert_base_two_completion_axioms baseTwoSynthesizedClockCoefficient_eq_complete
#print axioms baseTwoSynthesizedClockCoefficient_eq_complete
#assert_base_two_completion_axioms baseTwoCompletedClockJet_cutoff_independent
#print axioms baseTwoCompletedClockJet_cutoff_independent
#assert_base_two_completion_axioms baseTwoSynthesizedTailCoefficient
#print axioms baseTwoSynthesizedTailCoefficient
#assert_base_two_completion_axioms baseTwoHeadCoefficient_add_synthesizedTailCoefficient
#print axioms baseTwoHeadCoefficient_add_synthesizedTailCoefficient
#assert_base_two_completion_axioms baseTwoSynthesizedTailCoefficient_eq_jetResidual
#print axioms baseTwoSynthesizedTailCoefficient_eq_jetResidual
#assert_base_two_completion_axioms baseTwoSynthesizedTailCoefficient_cutoff_balance
#print axioms baseTwoSynthesizedTailCoefficient_cutoff_balance
#assert_base_two_completion_axioms baseTwoCompletedClockSeries
#print axioms baseTwoCompletedClockSeries
#assert_base_two_completion_axioms baseTwoSynthesizedTailSeries
#print axioms baseTwoSynthesizedTailSeries
#assert_base_two_completion_axioms baseTwoCompletedClockSeries_coeff
#print axioms baseTwoCompletedClockSeries_coeff
#assert_base_two_completion_axioms baseTwoSynthesizedTailSeries_coeff
#print axioms baseTwoSynthesizedTailSeries_coeff
#assert_base_two_completion_axioms baseTwoHeadSeries_add_synthesizedTailSeries
#print axioms baseTwoHeadSeries_add_synthesizedTailSeries
#assert_base_two_completion_axioms baseTwoSynthesizedTailSeries_unique
#print axioms baseTwoSynthesizedTailSeries_unique
#assert_base_two_completion_axioms baseTwoCompletedClockCoefficient_zero
#print axioms baseTwoCompletedClockCoefficient_zero
#assert_base_two_completion_axioms baseTwoSynthesizedTailCoefficient_zero
#print axioms baseTwoSynthesizedTailCoefficient_zero

end GeometryOfNumbers.Analysis.BaseTwoCompletion
