import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoCenterLegSynthesis_adjoint_apply
#print axioms baseTwoCenterLegSynthesis_adjoint_apply
#assert_analysis_axioms baseTwoCenterLegSynthesis_adjoint_comp_self
#print axioms baseTwoCenterLegSynthesis_adjoint_comp_self
#assert_analysis_axioms baseTwoPhysicalToSeeded
#print axioms baseTwoPhysicalToSeeded
#assert_analysis_axioms baseTwoPhysicalToSeeded_apply
#print axioms baseTwoPhysicalToSeeded_apply
#assert_analysis_axioms baseTwoPhysicalToSeeded_norm
#print axioms baseTwoPhysicalToSeeded_norm
#assert_analysis_axioms baseTwoPhysicalCenterReconstruction
#print axioms baseTwoPhysicalCenterReconstruction
#assert_analysis_axioms baseTwoPhysicalCenterReconstruction_apply
#print axioms baseTwoPhysicalCenterReconstruction_apply
#assert_analysis_axioms baseTwoPhysicalCenterSelfCoupling_factorization
#print axioms baseTwoPhysicalCenterSelfCoupling_factorization
#assert_analysis_axioms baseTwoPhysicalCenterReconstruction_deltaRight_zero
#print axioms baseTwoPhysicalCenterReconstruction_deltaRight_zero
#assert_analysis_axioms baseTwoCenterLegSynthesis_adjoint_deltaRight
#print axioms baseTwoCenterLegSynthesis_adjoint_deltaRight
#assert_analysis_axioms baseTwoCenterLegSynthesis_adjoint_deltaRight_explicit
#print axioms baseTwoCenterLegSynthesis_adjoint_deltaRight_explicit
#assert_analysis_axioms baseTwoCenterLegSynthesis_adjoint_deltaRight_ne_zero
#print axioms baseTwoCenterLegSynthesis_adjoint_deltaRight_ne_zero
#assert_analysis_axioms baseTwoPhysicalCenterReconstruction_ne_legSynthesis_adjoint
#print axioms baseTwoPhysicalCenterReconstruction_ne_legSynthesis_adjoint
end GeometryOfNumbers.Analysis.BaseTwoCompletion
