import GeometryOfNumbers.Analysis.BaseTwoCanonicalArchimedeanDressing
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_base_two_completion_axioms canonicalArchimedeanCompletionComplex
#print axioms canonicalArchimedeanCompletionComplex
#assert_base_two_completion_axioms canonicalArchimedeanCompletion
#print axioms canonicalArchimedeanCompletion
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_formula
#print axioms canonicalArchimedeanCompletion_formula
#assert_base_two_completion_axioms canonicalArchimedeanCompletionComplex_differentiableOn_ball
#print axioms canonicalArchimedeanCompletionComplex_differentiableOn_ball
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_analyticAt
#print axioms canonicalArchimedeanCompletion_analyticAt
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_contDiff
#print axioms canonicalArchimedeanCompletion_contDiff
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_zero
#print axioms canonicalArchimedeanCompletion_zero
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_zero_re_neg
#print axioms canonicalArchimedeanCompletion_zero_re_neg
#assert_base_two_completion_axioms canonicalArchimedeanCompletion_zero_ne_zero
#print axioms canonicalArchimedeanCompletion_zero_ne_zero
#assert_base_two_completion_axioms baseTwoCanonicalCompletionSeries
#print axioms baseTwoCanonicalCompletionSeries
#assert_base_two_completion_axioms baseTwoCanonicalCompletionSeries_coeff
#print axioms baseTwoCanonicalCompletionSeries_coeff
#assert_base_two_completion_axioms baseTwoCanonicalCompletionSeries_constantCoeff
#print axioms baseTwoCanonicalCompletionSeries_constantCoeff
#assert_base_two_completion_axioms baseTwoCanonicalCompletionSeries_constantCoeff_ne_zero
#print axioms baseTwoCanonicalCompletionSeries_constantCoeff_ne_zero
end GeometryOfNumbers.Analysis.BaseTwoCompletion
