import GeometryOfNumbers.Analysis.BaseTwoCompletedBoundaryHilbert
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms BaseTwoCompletedBoundaryHilbertCarrier
#print axioms BaseTwoCompletedBoundaryHilbertCarrier
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertPrefixState
#print axioms baseTwoCompletedBoundaryHilbertPrefixState
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertState
#print axioms baseTwoCompletedBoundaryHilbertState
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertState_seed
#print axioms baseTwoCompletedBoundaryHilbertState_seed
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertState_interior
#print axioms baseTwoCompletedBoundaryHilbertState_interior
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertState_boundary
#print axioms baseTwoCompletedBoundaryHilbertState_boundary
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertPrefixState_tendsto
#print axioms baseTwoCompletedBoundaryHilbertPrefixState_tendsto
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertReadout
#print axioms baseTwoCompletedBoundaryHilbertReadout
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertReadout_apply
#print axioms baseTwoCompletedBoundaryHilbertReadout_apply
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertReadout_eq_signal
#print axioms baseTwoCompletedBoundaryHilbertReadout_eq_signal
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertReadout_eq_banachReadout
#print axioms baseTwoCompletedBoundaryHilbertReadout_eq_banachReadout
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertPrefixState_readout
#print axioms baseTwoCompletedBoundaryHilbertPrefixState_readout
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertPrefixState_readout_tendsto
#print axioms baseTwoCompletedBoundaryHilbertPrefixState_readout_tendsto
end GeometryOfNumbers.Analysis.BaseTwoCompletion
