import GeometryOfNumbers.Analysis.BaseTwoCompletedVectorLiftGate
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms canonicalArchimedeanCompletion_ne_zero
#print axioms canonicalArchimedeanCompletion_ne_zero
#assert_analysis_axioms baseTwoCanonicalDressingScalar
#print axioms baseTwoCanonicalDressingScalar
#assert_analysis_axioms baseTwoCanonicalDressingScalar_ne_zero
#print axioms baseTwoCanonicalDressingScalar_ne_zero
#assert_analysis_axioms baseTwoCanonicalDressingScalar_analyticAt
#print axioms baseTwoCanonicalDressingScalar_analyticAt
#assert_analysis_axioms baseTwoCanonicalResponse_eq_dressing_mul_signal
#print axioms baseTwoCanonicalResponse_eq_dressing_mul_signal
#assert_analysis_axioms baseTwoVectorDressing
#print axioms baseTwoVectorDressing
#assert_analysis_axioms baseTwoVectorDressing_apply
#print axioms baseTwoVectorDressing_apply
#assert_analysis_axioms baseTwoVectorDressing_norm
#print axioms baseTwoVectorDressing_norm
#assert_analysis_axioms baseTwoVectorDressing_injective
#print axioms baseTwoVectorDressing_injective
#assert_analysis_axioms baseTwoVectorDressing_readout_residual
#print axioms baseTwoVectorDressing_readout_residual
#assert_analysis_axioms baseTwoVectorDressing_readout_eq_response_iff
#print axioms baseTwoVectorDressing_readout_eq_response_iff
#assert_analysis_axioms baseTwoVectorDressing_function_readout_iff
#print axioms baseTwoVectorDressing_function_readout_iff
#assert_analysis_axioms baseTwoVectorDressing_hasDerivAt
#print axioms baseTwoVectorDressing_hasDerivAt
#assert_analysis_axioms baseTwoVectorDressing_clock_derivative_residual
#print axioms baseTwoVectorDressing_clock_derivative_residual
#assert_analysis_axioms baseTwoVectorDressing_same_clock_iff
#print axioms baseTwoVectorDressing_same_clock_iff
#assert_analysis_axioms baseTwoGreenVectorDressing
#print axioms baseTwoGreenVectorDressing
#assert_analysis_axioms baseTwoDressedFiniteOrbit_add_tail
#print axioms baseTwoDressedFiniteOrbit_add_tail
#assert_analysis_axioms baseTwoVectorDressing_parseval
#print axioms baseTwoVectorDressing_parseval
end GeometryOfNumbers.Analysis.BaseTwoCompletion
