import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms BaseTwoSeededMaterialHilbert
#print axioms BaseTwoSeededMaterialHilbert
#assert_analysis_axioms PhysicalEdgeL2
#print axioms PhysicalEdgeL2
#assert_analysis_axioms baseTwoCenterReconstruction
#print axioms baseTwoCenterReconstruction
#assert_analysis_axioms baseTwoCenterLogGap
#print axioms baseTwoCenterLogGap
#assert_analysis_axioms baseTwoCenterCouplingRaw
#print axioms baseTwoCenterCouplingRaw
#assert_analysis_axioms baseTwoConcreteSeededGradientState
#print axioms baseTwoConcreteSeededGradientState
#assert_analysis_axioms baseTwoCenterReconstruction_concrete
#print axioms baseTwoCenterReconstruction_concrete
#assert_analysis_axioms baseTwoCenterCouplingRaw_concrete
#print axioms baseTwoCenterCouplingRaw_concrete
#assert_analysis_axioms baseTwoCenterCouplingSeedRaw
#print axioms baseTwoCenterCouplingSeedRaw
#assert_analysis_axioms baseTwoCenterCouplingPhysicalRaw
#print axioms baseTwoCenterCouplingPhysicalRaw
#assert_analysis_axioms baseTwoCenterCouplingResidualRaw
#print axioms baseTwoCenterCouplingResidualRaw
#assert_analysis_axioms baseTwoCenterCouplingRaw_seed_physical_residual
#print axioms baseTwoCenterCouplingRaw_seed_physical_residual
#assert_analysis_axioms baseTwoPhysicalEdgeEmbedding
#print axioms baseTwoPhysicalEdgeEmbedding
#assert_analysis_axioms baseTwoPhysicalEdgeEmbedding_apply
#print axioms baseTwoPhysicalEdgeEmbedding_apply
#assert_analysis_axioms baseTwoPhysicalEdgeEmbedding_off_sector
#print axioms baseTwoPhysicalEdgeEmbedding_off_sector
#assert_analysis_axioms baseTwoPhysicalEdgeRestriction_embedding
#print axioms baseTwoPhysicalEdgeRestriction_embedding
#assert_analysis_axioms baseTwoPhysicalEdgeEmbedding_restriction
#print axioms baseTwoPhysicalEdgeEmbedding_restriction
#assert_analysis_axioms baseTwoPhysicalEdgeProjection_embedding
#print axioms baseTwoPhysicalEdgeProjection_embedding
#assert_analysis_axioms baseTwoPhysicalCenterSelfCouplingRaw
#print axioms baseTwoPhysicalCenterSelfCouplingRaw
#assert_analysis_axioms baseTwoPhysicalCenterSelfCouplingRaw_first_cell
#print axioms baseTwoPhysicalCenterSelfCouplingRaw_first_cell
#assert_analysis_axioms baseTwoPhysicalCenterDeltaLeft
#print axioms baseTwoPhysicalCenterDeltaLeft
#assert_analysis_axioms baseTwoPhysicalCenterDeltaRight
#print axioms baseTwoPhysicalCenterDeltaRight
#assert_analysis_axioms baseTwoPhysicalCenterSelfCouplingRaw_deltaLeft_first_cell
#print axioms baseTwoPhysicalCenterSelfCouplingRaw_deltaLeft_first_cell
#assert_analysis_axioms baseTwoPhysicalCenterSelfCouplingRaw_deltaRight_first_cell
#print axioms baseTwoPhysicalCenterSelfCouplingRaw_deltaRight_first_cell
end GeometryOfNumbers.Analysis.BaseTwoCompletion
