import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoPhysicalEdgeRestriction
#print axioms baseTwoPhysicalEdgeRestriction
#assert_analysis_axioms baseTwoPhysicalEdgeRestriction_apply
#print axioms baseTwoPhysicalEdgeRestriction_apply
#assert_analysis_axioms baseTwoPhysicalEdgeRestriction_norm_le
#print axioms baseTwoPhysicalEdgeRestriction_norm_le
#assert_analysis_axioms baseTwoMaterialEdgeRealification
#print axioms baseTwoMaterialEdgeRealification
#assert_analysis_axioms baseTwoMaterialEdgeRealification_pack
#print axioms baseTwoMaterialEdgeRealification_pack
#assert_analysis_axioms baseTwoMaterialEdgeRealification_neg_I
#print axioms baseTwoMaterialEdgeRealification_neg_I
#assert_analysis_axioms baseTwoPhysicalEdgeC2State
#print axioms baseTwoPhysicalEdgeC2State
#assert_analysis_axioms baseTwoPhysicalEdgeC2State_apply
#print axioms baseTwoPhysicalEdgeC2State_apply
#assert_analysis_axioms baseTwoPhysicalEdgeC2State_apply_edge
#print axioms baseTwoPhysicalEdgeC2State_apply_edge
#assert_analysis_axioms baseTwoPhysicalEdgeC2State_norm_le
#print axioms baseTwoPhysicalEdgeC2State_norm_le
#assert_analysis_axioms baseTwoPhysicalEdgeProjection
#print axioms baseTwoPhysicalEdgeProjection
#assert_analysis_axioms baseTwoResidualEdgeProjection
#print axioms baseTwoResidualEdgeProjection
#assert_analysis_axioms baseTwoResidualEdgePredicate
#print axioms baseTwoResidualEdgePredicate
#assert_analysis_axioms baseTwoPhysicalResidual_reconstruction
#print axioms baseTwoPhysicalResidual_reconstruction
#assert_analysis_axioms baseTwoPhysicalResidual_orthogonal
#print axioms baseTwoPhysicalResidual_orthogonal
#assert_analysis_axioms baseTwoPhysicalResidual_norm_sq
#print axioms baseTwoPhysicalResidual_norm_sq
#assert_analysis_axioms baseTwoPhysicalEdgeC2State_projection
#print axioms baseTwoPhysicalEdgeC2State_projection
#assert_analysis_axioms baseTwoPhysicalResidualC2_injective
#print axioms baseTwoPhysicalResidualC2_injective
#assert_analysis_axioms baseTwoPhysicalEdgeC2State_norm_sq_projection
#print axioms baseTwoPhysicalEdgeC2State_norm_sq_projection
#assert_analysis_axioms baseTwoPhysicalC2Residual_norm_sq
#print axioms baseTwoPhysicalC2Residual_norm_sq
#assert_analysis_axioms baseTwoPhysicalOrdinaryC2State
#print axioms baseTwoPhysicalOrdinaryC2State
#assert_analysis_axioms baseTwoPhysicalLogGradientC2State
#print axioms baseTwoPhysicalLogGradientC2State
#assert_analysis_axioms baseTwoPhysicalOrdinaryC2State_apply
#print axioms baseTwoPhysicalOrdinaryC2State_apply
#assert_analysis_axioms baseTwoPhysicalLogGradientC2State_apply
#print axioms baseTwoPhysicalLogGradientC2State_apply
#assert_analysis_axioms baseTwoPhysicalOrdinaryC2State_hasDerivAt
#print axioms baseTwoPhysicalOrdinaryC2State_hasDerivAt
#assert_analysis_axioms baseTwoCompletedBoundaryValue_eq_physicalChannel
#print axioms baseTwoCompletedBoundaryValue_eq_physicalChannel
#assert_analysis_axioms summable_baseTwoPhysicalCellReturn
#print axioms summable_baseTwoPhysicalCellReturn
#assert_analysis_axioms baseTwoPhysicalOrdinaryTfvd
#print axioms baseTwoPhysicalOrdinaryTfvd
#assert_analysis_axioms baseTwoPhysicalLogGradientTfvd
#print axioms baseTwoPhysicalLogGradientTfvd
#assert_analysis_axioms baseTwoPhysicalOrdinaryTfvd_synthesis
#print axioms baseTwoPhysicalOrdinaryTfvd_synthesis
#assert_analysis_axioms baseTwoPhysicalLogGradientTfvd_synthesis
#print axioms baseTwoPhysicalLogGradientTfvd_synthesis
#assert_analysis_axioms baseTwoPhysicalResidualTfvdAnalysis
#print axioms baseTwoPhysicalResidualTfvdAnalysis
#assert_analysis_axioms baseTwoPhysicalResidualTfvdAnalysis_injective
#print axioms baseTwoPhysicalResidualTfvdAnalysis_injective
#assert_analysis_axioms baseTwoCompletedPhysicalResidualTfvdPair
#print axioms baseTwoCompletedPhysicalResidualTfvdPair
#assert_analysis_axioms baseTwoCompletedPhysicalResidualTfvdPair_ordinary
#print axioms baseTwoCompletedPhysicalResidualTfvdPair_ordinary
#assert_analysis_axioms baseTwoCompletedPhysicalResidualTfvdPair_log
#print axioms baseTwoCompletedPhysicalResidualTfvdPair_log
#assert_analysis_axioms baseTwoCriticalPhysicalResidualTfvdPair
#print axioms baseTwoCriticalPhysicalResidualTfvdPair
#assert_analysis_axioms baseTwoCriticalPhysicalTfvd_synthesis
#print axioms baseTwoCriticalPhysicalTfvd_synthesis
#assert_analysis_axioms baseTwoPhysicalTfvdChannel
#print axioms baseTwoPhysicalTfvdChannel
#assert_analysis_axioms baseTwoPhysicalTfvdChannel_apply
#print axioms baseTwoPhysicalTfvdChannel_apply
#assert_analysis_axioms baseTwoPhysicalOrdinaryTfvd_hasDerivAt
#print axioms baseTwoPhysicalOrdinaryTfvd_hasDerivAt
end GeometryOfNumbers.Analysis.BaseTwoCompletion
