import GeometryOfNumbers.Analysis.BaseTwoRawL2ReadoutNonclosable
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoRawL2NormalizedWitness
#print axioms baseTwoRawL2NormalizedWitness
#assert_analysis_axioms baseTwoRawL2NormalizedWitness_norm_sq
#print axioms baseTwoRawL2NormalizedWitness_norm_sq
#assert_analysis_axioms baseTwoRawL2NormalizedWitness_tendsto
#print axioms baseTwoRawL2NormalizedWitness_tendsto
#assert_analysis_axioms baseTwoRawL2Witness_mem_graph
#print axioms baseTwoRawL2Witness_mem_graph
#assert_analysis_axioms baseTwoRawL2NormalizedWitness_mem_graph
#print axioms baseTwoRawL2NormalizedWitness_mem_graph
#assert_analysis_axioms baseTwoRawL2Readout_vertical_graph_limit
#print axioms baseTwoRawL2Readout_vertical_graph_limit
#assert_analysis_axioms baseTwoRawL2Readout_not_closable
#print axioms baseTwoRawL2Readout_not_closable
end GeometryOfNumbers.Analysis.BaseTwoCompletion
