import GeometryOfNumbers.Analysis.BaseTwoCanonicalDressingMoments
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_base_two_completion_axioms baseTwoCanonicalResponse
#print axioms baseTwoCanonicalResponse
#assert_base_two_completion_axioms baseTwoCanonicalResponseSeries
#print axioms baseTwoCanonicalResponseSeries
#assert_base_two_completion_axioms baseTwoCanonicalResponse_analyticAt
#print axioms baseTwoCanonicalResponse_analyticAt
#assert_base_two_completion_axioms baseTwoCanonicalResponseSeries_eq_normalizedJets
#print axioms baseTwoCanonicalResponseSeries_eq_normalizedJets
#assert_base_two_completion_axioms baseTwoCanonicalResponseSeries_coeff
#print axioms baseTwoCanonicalResponseSeries_coeff
#assert_base_two_completion_axioms baseTwoCanonicalClosedResponse_eq
#print axioms baseTwoCanonicalClosedResponse_eq
#assert_base_two_completion_axioms baseTwoCriticalCenterCell_zero_re_nonneg
#print axioms baseTwoCriticalCenterCell_zero_re_nonneg
#assert_base_two_completion_axioms baseTwoCriticalCompleteSignal_zero_re_pos
#print axioms baseTwoCriticalCompleteSignal_zero_re_pos
#assert_base_two_completion_axioms baseTwoCriticalCompleteSignal_zero_im
#print axioms baseTwoCriticalCompleteSignal_zero_im
#assert_base_two_completion_axioms baseTwoCanonicalPhi
#print axioms baseTwoCanonicalPhi
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment
#print axioms baseTwoCanonicalLogMoment
#assert_base_two_completion_axioms baseTwoCanonicalMomentSequence
#print axioms baseTwoCanonicalMomentSequence
#assert_base_two_completion_axioms baseTwoCanonicalPhi_eq_synthesized
#print axioms baseTwoCanonicalPhi_eq_synthesized
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_eq_synthesized
#print axioms baseTwoCanonicalLogMoment_eq_synthesized
#assert_base_two_completion_axioms baseTwoCanonicalMomentSequence_eq_logMoment
#print axioms baseTwoCanonicalMomentSequence_eq_logMoment
#assert_base_two_completion_axioms baseTwoCanonicalPhi_eq_normalizedEvenJet
#print axioms baseTwoCanonicalPhi_eq_normalizedEvenJet
#assert_base_two_completion_axioms baseTwoCanonicalPhi_zero_pos
#print axioms baseTwoCanonicalPhi_zero_pos
#assert_base_two_completion_axioms baseTwoCanonicalPhi_zero_ne_zero
#print axioms baseTwoCanonicalPhi_zero_ne_zero
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_isSequence
#print axioms baseTwoCanonicalLogMoment_isSequence
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_unique
#print axioms baseTwoCanonicalLogMoment_unique
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_formal_logDerivative
#print axioms baseTwoCanonicalLogMoment_formal_logDerivative
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_unique_of_formal_identity
#print axioms baseTwoCanonicalLogMoment_unique_of_formal_identity
#assert_base_two_completion_axioms baseTwoCanonicalLogMoment_cutoff_independent
#print axioms baseTwoCanonicalLogMoment_cutoff_independent
end GeometryOfNumbers.Analysis.BaseTwoCompletion
