import GeometryOfNumbers.Analysis.BaseTwoCanonicalCameraDressing
import GeometryOfNumbers.Analysis.BaseTwoExactHeadTailCompletionAudit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_base_two_completion_axioms baseTwoDressingParameter
#print axioms baseTwoDressingParameter
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorComplex
#print axioms baseTwoCanonicalCameraFactorComplex
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor
#print axioms baseTwoCanonicalCameraFactor
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor_formula
#print axioms baseTwoCanonicalCameraFactor_formula
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorComplex_differentiable
#print axioms baseTwoCanonicalCameraFactorComplex_differentiable
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor_analyticAt
#print axioms baseTwoCanonicalCameraFactor_analyticAt
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor_contDiff
#print axioms baseTwoCanonicalCameraFactor_contDiff
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor_ne_zero
#print axioms baseTwoCanonicalCameraFactor_ne_zero
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactor_zero
#print axioms baseTwoCanonicalCameraFactor_zero
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorSeries
#print axioms baseTwoCanonicalCameraFactorSeries
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorSeries_coeff
#print axioms baseTwoCanonicalCameraFactorSeries_coeff
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorSeries_constantCoeff
#print axioms baseTwoCanonicalCameraFactorSeries_constantCoeff
#assert_base_two_completion_axioms baseTwoCanonicalCameraFactorSeries_constantCoeff_ne_zero
#print axioms baseTwoCanonicalCameraFactorSeries_constantCoeff_ne_zero
end GeometryOfNumbers.Analysis.BaseTwoCompletion
