import GeometryOfNumbers.Analysis.BaseTwoCompletedBoundaryDynamics
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms criticalMaterialSample_hasDerivAt
#print axioms criticalMaterialSample_hasDerivAt
#assert_analysis_axioms criticalMaterialGradient_hasDerivAt
#print axioms criticalMaterialGradient_hasDerivAt
#assert_analysis_axioms baseTwoMaterialGradientDiagonalClockResidual
#print axioms baseTwoMaterialGradientDiagonalClockResidual
#assert_analysis_axioms criticalMaterialGradient_deriv_eq_diagonalClock_add_residual
#print axioms criticalMaterialGradient_deriv_eq_diagonalClock_add_residual
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertClockCoordinate
#print axioms baseTwoCompletedBoundaryHilbertClockCoordinate
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertClockCoordinate_eq
#print axioms baseTwoCompletedBoundaryHilbertClockCoordinate_eq
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertInterior_coordinate_hasDerivAt
#print axioms baseTwoCompletedBoundaryHilbertInterior_coordinate_hasDerivAt
#assert_analysis_axioms baseTwoMaterialGradientDiagonalClockResidual_zeroEdge_ne_zero
#print axioms baseTwoMaterialGradientDiagonalClockResidual_zeroEdge_ne_zero
#assert_analysis_axioms criticalMaterialGradient_deriv_zeroEdge_ne_diagonalClock
#print axioms criticalMaterialGradient_deriv_zeroEdge_ne_diagonalClock
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertSeed_hasDerivAt
#print axioms baseTwoCompletedBoundaryHilbertSeed_hasDerivAt
#assert_analysis_axioms baseTwoCompletedBoundaryValue_hasDerivAt
#print axioms baseTwoCompletedBoundaryValue_hasDerivAt
end GeometryOfNumbers.Analysis.BaseTwoCompletion

noncomputable section
-- Verify the standard complete Hilbert instances, not merely a normed product.
example : InnerProductSpace ℂ
    GeometryOfNumbers.Analysis.BaseTwoCompletion.BaseTwoCompletedBoundaryHilbertCarrier :=
  inferInstance
example : CompleteSpace
    GeometryOfNumbers.Analysis.BaseTwoCompletion.BaseTwoCompletedBoundaryHilbertCarrier :=
  inferInstance
