import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms BaseTwoPhysicalEdge
#print axioms BaseTwoPhysicalEdge
#assert_analysis_axioms baseTwoPhysicalEdgeIndex
#print axioms baseTwoPhysicalEdgeIndex
#assert_analysis_axioms baseTwoPhysicalEdgeIndex_left
#print axioms baseTwoPhysicalEdgeIndex_left
#assert_analysis_axioms baseTwoPhysicalEdgeIndex_right
#print axioms baseTwoPhysicalEdgeIndex_right
#assert_analysis_axioms baseTwoPhysicalEdgeIndex_injective
#print axioms baseTwoPhysicalEdgeIndex_injective
#assert_analysis_axioms baseTwoPhysicalEdgeIndex_range
#print axioms baseTwoPhysicalEdgeIndex_range
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint
#print axioms baseTwoPhysicalEdgeOddEndpoint
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint_left
#print axioms baseTwoPhysicalEdgeOddEndpoint_left
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint_right
#print axioms baseTwoPhysicalEdgeOddEndpoint_right
#assert_analysis_axioms oddMaterialPhysicalEdge
#print axioms oddMaterialPhysicalEdge
#assert_analysis_axioms oddMaterialPhysicalEdge_endpoint
#print axioms oddMaterialPhysicalEdge_endpoint
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint_decode
#print axioms baseTwoPhysicalEdgeOddEndpoint_decode
#assert_analysis_axioms baseTwoPhysicalEdgeEquivOddMaterial
#print axioms baseTwoPhysicalEdgeEquivOddMaterial
#assert_analysis_axioms baseTwoPhysicalEdgeEquivC2Address
#print axioms baseTwoPhysicalEdgeEquivC2Address
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address
#print axioms baseTwoPhysicalEdgeC2Address
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address_eq
#print axioms baseTwoPhysicalEdgeC2Address_eq
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address_material
#print axioms baseTwoPhysicalEdgeC2Address_material
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint_neighbor
#print axioms baseTwoPhysicalEdgeOddEndpoint_neighbor
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address_direction
#print axioms baseTwoPhysicalEdgeC2Address_direction
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address_depth
#print axioms baseTwoPhysicalEdgeC2Address_depth
#assert_analysis_axioms baseTwoPhysicalEdgeC2Address_center
#print axioms baseTwoPhysicalEdgeC2Address_center
#assert_analysis_axioms baseTwoPhysicalEdgeOddEndpoint_incidence
#print axioms baseTwoPhysicalEdgeOddEndpoint_incidence
end GeometryOfNumbers.Analysis.BaseTwoCompletion
