import GeometryOfNumbers.Analysis.C2RealFiberTfvdIncidence
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms C2RealVerticalChannels
#print axioms C2RealVerticalChannels
#assert_analysis_axioms C2RealTfvdChannels
#print axioms C2RealTfvdChannels
#assert_analysis_axioms c2BranchVerticalCoordinate
#print axioms c2BranchVerticalCoordinate
#assert_analysis_axioms c2BranchVerticalCoordinate_apply
#print axioms c2BranchVerticalCoordinate_apply
#assert_analysis_axioms c2BranchVerticalCoordinates
#print axioms c2BranchVerticalCoordinates
#assert_analysis_axioms c2BranchVerticalCoordinates_injective
#print axioms c2BranchVerticalCoordinates_injective
#assert_analysis_axioms c2FiberTfvdAnalysis
#print axioms c2FiberTfvdAnalysis
#assert_analysis_axioms c2FiberTfvdSynthesis
#print axioms c2FiberTfvdSynthesis
#assert_analysis_axioms c2FiberTfvdSynthesis_analysis
#print axioms c2FiberTfvdSynthesis_analysis
#assert_analysis_axioms c2FiberTfvdAnalysis_injective
#print axioms c2FiberTfvdAnalysis_injective
#assert_analysis_axioms c2OddMaterialTfvdAnalysis
#print axioms c2OddMaterialTfvdAnalysis
#assert_analysis_axioms c2OddMaterialTfvdAnalysis_injective
#print axioms c2OddMaterialTfvdAnalysis_injective
#assert_analysis_axioms c2OddMaterial_verticalCoordinate
#print axioms c2OddMaterial_verticalCoordinate
#assert_analysis_axioms c2UnitOddCore
#print axioms c2UnitOddCore
#assert_analysis_axioms c2ParityIncidenceAddress
#print axioms c2ParityIncidenceAddress
#assert_analysis_axioms c2ParityIncidenceAddress_injective
#print axioms c2ParityIncidenceAddress_injective
#assert_analysis_axioms c2ParityIncidenceCenter
#print axioms c2ParityIncidenceCenter
#assert_analysis_axioms c2ParityIncidenceLeg
#print axioms c2ParityIncidenceLeg
#assert_analysis_axioms c2ParityIncidence_left
#print axioms c2ParityIncidence_left
#assert_analysis_axioms c2ParityIncidence_right
#print axioms c2ParityIncidence_right
#assert_analysis_axioms c2ParityIncidence_depth_recovery
#print axioms c2ParityIncidence_depth_recovery
#assert_analysis_axioms c2ParityIncidence_center_ne_leg
#print axioms c2ParityIncidence_center_ne_leg
#assert_analysis_axioms c2RealIncidenceJet
#print axioms c2RealIncidenceJet
#assert_analysis_axioms c2RealIncidenceJet_linearIndependent
#print axioms c2RealIncidenceJet_linearIndependent
#assert_analysis_axioms c2RealTfvdIncidenceJet
#print axioms c2RealTfvdIncidenceJet
#assert_analysis_axioms c2RealTfvdIncidenceJet_linearIndependent
#print axioms c2RealTfvdIncidenceJet_linearIndependent
#assert_analysis_axioms c2RealTfvdIncidenceJet_even_linearIndependent
#print axioms c2RealTfvdIncidenceJet_even_linearIndependent
#assert_analysis_axioms c2RealTfvdIncidenceJet_odd_linearIndependent
#print axioms c2RealTfvdIncidenceJet_odd_linearIndependent
#assert_analysis_axioms c2RealTfvdIncidenceJet_even_prefix_linearIndependent
#print axioms c2RealTfvdIncidenceJet_even_prefix_linearIndependent
#assert_analysis_axioms c2RealTfvdIncidenceJet_odd_prefix_linearIndependent
#print axioms c2RealTfvdIncidenceJet_odd_prefix_linearIndependent
#assert_analysis_axioms c2CriticalOddMaterialTfvdAnalysis_injective
#print axioms c2CriticalOddMaterialTfvdAnalysis_injective
end GeometryOfNumbers.Analysis
