import GeometryOfNumbers.Analysis.CanonicalGreenMomentJetSeam
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.CanonicalGreenMomentSeam
#assert_analysis_axioms greenParseval_differentiableAt_iff
#print axioms greenParseval_differentiableAt_iff
#assert_analysis_axioms greenParseval_deriv
#print axioms greenParseval_deriv
#assert_analysis_axioms greenParseval_iteratedDeriv
#print axioms greenParseval_iteratedDeriv
#assert_analysis_axioms greenParseval_contDiffAt_iff
#print axioms greenParseval_contDiffAt_iff
#assert_analysis_axioms greenParseval_inner_real
#print axioms greenParseval_inner_real
#assert_analysis_axioms greenParseval_parityMomentGram_iff
#print axioms greenParseval_parityMomentGram_iff
#assert_analysis_axioms c2MaterialOrbitJet
#print axioms c2MaterialOrbitJet
#assert_analysis_axioms c2ParsevalOrbitJet
#print axioms c2ParsevalOrbitJet
#assert_analysis_axioms c2ParsevalOrbitJet_eq_transport
#print axioms c2ParsevalOrbitJet_eq_transport
#assert_analysis_axioms c2ParsevalOrbitJet_inner
#print axioms c2ParsevalOrbitJet_inner
#assert_analysis_axioms c2ParsevalOrbit_differentiableAt_zero_iff_log_moment
#print axioms c2ParsevalOrbit_differentiableAt_zero_iff_log_moment
#assert_analysis_axioms c2ParsevalOrbit_contDiffAt_iff
#print axioms c2ParsevalOrbit_contDiffAt_iff
#assert_analysis_axioms c2ParsevalOrbitFirstColumn
#print axioms c2ParsevalOrbitFirstColumn
#assert_analysis_axioms baseTwoCanonicalGreenFirstColumnResidual
#print axioms baseTwoCanonicalGreenFirstColumnResidual
#assert_analysis_axioms c2ParsevalOrbitFirstColumn_eq_material
#print axioms c2ParsevalOrbitFirstColumn_eq_material
#assert_analysis_axioms baseTwoCanonicalGreenFirstColumnResidual_eq_material
#print axioms baseTwoCanonicalGreenFirstColumnResidual_eq_material
#assert_analysis_axioms c2ParsevalOrbitFirstColumn_zero
#print axioms c2ParsevalOrbitFirstColumn_zero
#assert_analysis_axioms baseTwoCanonicalGreenFirstColumnResidual_zero
#print axioms baseTwoCanonicalGreenFirstColumnResidual_zero
end GeometryOfNumbers.Analysis.CanonicalGreenMomentSeam
