import GeometryOfNumbers.Analysis.Audit

-- Complete TFVD channel observation: own PosDef is distinct from moment Hankel.
namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms CompleteVerticalObservationCarrier
#print axioms CompleteVerticalObservationCarrier
#assert_analysis_axioms completeVerticalObservation
#print axioms completeVerticalObservation
#assert_analysis_axioms completeVerticalObservation_apply
#print axioms completeVerticalObservation_apply
#assert_analysis_axioms completeVerticalObservation_reconstruction
#print axioms completeVerticalObservation_reconstruction
#assert_analysis_axioms completeVerticalObservation_injective
#print axioms completeVerticalObservation_injective
#assert_analysis_axioms completeVerticalObservationJet
#print axioms completeVerticalObservationJet
#assert_analysis_axioms completeVerticalObservationJet_c2_provenance
#print axioms completeVerticalObservationJet_c2_provenance
#assert_analysis_axioms completeVerticalObservationJet_linearIndependent
#print axioms completeVerticalObservationJet_linearIndependent
#assert_analysis_axioms completeVerticalPrefixObservation
#print axioms completeVerticalPrefixObservation
#assert_analysis_axioms completeVerticalPrefixObservation_injective
#print axioms completeVerticalPrefixObservation_injective
#assert_analysis_axioms completeVerticalObservabilityGram
#print axioms completeVerticalObservabilityGram
#assert_analysis_axioms completeVerticalObservabilityGram_posDef
#print axioms completeVerticalObservabilityGram_posDef
#assert_analysis_axioms completeVerticalObservationJet_inner_zero_zero
#print axioms completeVerticalObservationJet_inner_zero_zero
#assert_analysis_axioms completeVerticalObservationJet_inner_zero_one
#print axioms completeVerticalObservationJet_inner_zero_one
#assert_analysis_axioms completeVerticalObservationJet_inner_zero_two
#print axioms completeVerticalObservationJet_inner_zero_two
#assert_analysis_axioms completeVerticalObservationJet_inner_one_one
#print axioms completeVerticalObservationJet_inner_one_one
#assert_analysis_axioms completeVerticalObservabilityGram_not_hankel
#print axioms completeVerticalObservabilityGram_not_hankel
#assert_analysis_axioms completeVerticalObservationJet_not_momentGram
#print axioms completeVerticalObservationJet_not_momentGram
#assert_analysis_axioms completeCriticalVerticalObservabilityGram_not_canonicalHankel
#print axioms completeCriticalVerticalObservabilityGram_not_canonicalHankel
end GeometryOfNumbers.Analysis
