import GeometryOfNumbers.Analysis.CompletedBoundaryTransportedClock
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms completedBoundaryClockCoordinates
#print axioms completedBoundaryClockCoordinates
#assert_analysis_axioms completedBoundaryCellReturnCoordinates
#print axioms completedBoundaryCellReturnCoordinates
#assert_analysis_axioms completedBoundaryClockCellCoordinates
#print axioms completedBoundaryClockCellCoordinates
#assert_analysis_axioms completedBoundaryTransportedClockDomain
#print axioms completedBoundaryTransportedClockDomain
#assert_analysis_axioms completedBoundaryTransportedClock
#print axioms completedBoundaryTransportedClock
#assert_analysis_axioms completedBoundaryTransportedClock_seed
#print axioms completedBoundaryTransportedClock_seed
#assert_analysis_axioms completedBoundaryTransportedClock_interior
#print axioms completedBoundaryTransportedClock_interior
#assert_analysis_axioms completedBoundaryTransportedClock_boundary
#print axioms completedBoundaryTransportedClock_boundary
#assert_analysis_axioms completedBoundaryTransportedClock_image_boundary
#print axioms completedBoundaryTransportedClock_image_boundary
#assert_analysis_axioms baseTwoCompletedBoundaryHilbertState_mem_clockDomain
#print axioms baseTwoCompletedBoundaryHilbertState_mem_clockDomain
#assert_analysis_axioms completedBoundaryState_hasDerivAt_clock
#print axioms completedBoundaryState_hasDerivAt_clock
#assert_analysis_axioms completedBoundaryMaterialDeltaOne
#print axioms completedBoundaryMaterialDeltaOne
#assert_analysis_axioms completedBoundaryMaterialDeltaTwo
#print axioms completedBoundaryMaterialDeltaTwo
#assert_analysis_axioms completedBoundaryMaterialDeltaOne_mem_domain
#print axioms completedBoundaryMaterialDeltaOne_mem_domain
#assert_analysis_axioms completedBoundaryMaterialDeltaTwo_mem_domain
#print axioms completedBoundaryMaterialDeltaTwo_mem_domain
#assert_analysis_axioms completedBoundaryTransportedClock_deltaOne
#print axioms completedBoundaryTransportedClock_deltaOne
#assert_analysis_axioms completedBoundaryTransportedClock_deltaTwo
#print axioms completedBoundaryTransportedClock_deltaTwo
#assert_analysis_axioms completedBoundaryMaterialDelta_inner
#print axioms completedBoundaryMaterialDelta_inner
#assert_analysis_axioms completedBoundaryTransportedClock_not_standard_symmetric
#print axioms completedBoundaryTransportedClock_not_standard_symmetric
#assert_analysis_axioms completedBoundaryTransportedClock_not_selfAdjoint
#print axioms completedBoundaryTransportedClock_not_selfAdjoint
end GeometryOfNumbers.Analysis.BaseTwoCompletion
