import GeometryOfNumbers.Analysis.CompletedClockCandidateObstructions
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms criticalMaterialSample_norm_sq
#print axioms criticalMaterialSample_norm_sq
#assert_analysis_axioms criticalMaterialSample_not_memℓp
#print axioms criticalMaterialSample_not_memℓp
#assert_analysis_axioms c2PhysicalSource_unitCore_left_energy_ratio
#print axioms c2PhysicalSource_unitCore_left_energy_ratio
#assert_analysis_axioms no_direct_c2PhysicalSource_match
#print axioms no_direct_c2PhysicalSource_match
#assert_analysis_axioms completedClock_isometric_intertwiner_impossible
#print axioms completedClock_isometric_intertwiner_impossible
end GeometryOfNumbers.Analysis.BaseTwoCompletion
