import GeometryOfNumbers.Analysis.CompletedMaterialGradientStrongClock
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms baseTwoComplexMaterialGradient
#print axioms baseTwoComplexMaterialGradient
#assert_analysis_axioms baseTwoComplexMaterialGradient_ofReal
#print axioms baseTwoComplexMaterialGradient_ofReal
#assert_analysis_axioms baseTwoComplexMaterialGradient_norm_le
#print axioms baseTwoComplexMaterialGradient_norm_le
#assert_analysis_axioms baseTwoComplexMaterialGradientLp
#print axioms baseTwoComplexMaterialGradientLp
#assert_analysis_axioms baseTwoComplexMaterialGradientLp_differentiableOn_ball
#print axioms baseTwoComplexMaterialGradientLp_differentiableOn_ball
#assert_analysis_axioms baseTwoComplexMaterialGradientLp_ofReal
#print axioms baseTwoComplexMaterialGradientLp_ofReal
#assert_analysis_axioms baseTwoCompletedMaterialGradient_differentiableAt
#print axioms baseTwoCompletedMaterialGradient_differentiableAt
#assert_analysis_axioms baseTwoCompletedMaterialGradientL2_differentiableAt
#print axioms baseTwoCompletedMaterialGradientL2_differentiableAt
#assert_analysis_axioms baseTwoCompletedMaterialGradient_deriv_apply
#print axioms baseTwoCompletedMaterialGradient_deriv_apply
#assert_analysis_axioms baseTwoCompletedMaterialGradientL2_deriv_apply
#print axioms baseTwoCompletedMaterialGradientL2_deriv_apply
#assert_analysis_axioms baseTwoCompletedMaterialClock_memLp_one
#print axioms baseTwoCompletedMaterialClock_memLp_one
#assert_analysis_axioms baseTwoCompletedMaterialClockL1
#print axioms baseTwoCompletedMaterialClockL1
#assert_analysis_axioms baseTwoCompletedMaterialClockL2
#print axioms baseTwoCompletedMaterialClockL2
#assert_analysis_axioms baseTwoCompletedMaterialClockL1_apply
#print axioms baseTwoCompletedMaterialClockL1_apply
#assert_analysis_axioms baseTwoCompletedMaterialClockL2_apply
#print axioms baseTwoCompletedMaterialClockL2_apply
#assert_analysis_axioms baseTwoCompletedMaterialGradient_hasDerivAt_clock
#print axioms baseTwoCompletedMaterialGradient_hasDerivAt_clock
#assert_analysis_axioms baseTwoCompletedMaterialGradientL2_hasDerivAt_clock
#print axioms baseTwoCompletedMaterialGradientL2_hasDerivAt_clock
#assert_analysis_axioms baseTwoCompletedBoundaryClockReturn
#print axioms baseTwoCompletedBoundaryClockReturn
#assert_analysis_axioms summable_baseTwoCompletedBoundaryClockReturn
#print axioms summable_baseTwoCompletedBoundaryClockReturn
#assert_analysis_axioms baseTwoCompletedBoundaryValue_hasDerivAt_clock
#print axioms baseTwoCompletedBoundaryValue_hasDerivAt_clock
end GeometryOfNumbers.Analysis.BaseTwoCompletion
