import GeometryOfNumbers.Analysis.FiniteSeedGradientClock
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms FiniteSeedGradientCarrier
#print axioms FiniteSeedGradientCarrier
#assert_analysis_axioms finiteGradientPrefix
#print axioms finiteGradientPrefix
#assert_analysis_axioms finiteGradientPrefix_zero
#print axioms finiteGradientPrefix_zero
#assert_analysis_axioms finiteGradientPrefix_succ
#print axioms finiteGradientPrefix_succ
#assert_analysis_axioms finiteSeedGradientEncode
#print axioms finiteSeedGradientEncode
#assert_analysis_axioms finiteSeedGradientDecode
#print axioms finiteSeedGradientDecode
#assert_analysis_axioms finiteSeedGradientEncode_seed
#print axioms finiteSeedGradientEncode_seed
#assert_analysis_axioms finiteSeedGradientEncode_gradient
#print axioms finiteSeedGradientEncode_gradient
#assert_analysis_axioms finiteSeedGradientDecode_apply
#print axioms finiteSeedGradientDecode_apply
#assert_analysis_axioms finiteSeedGradientDecode_encode
#print axioms finiteSeedGradientDecode_encode
#assert_analysis_axioms finiteSeedGradientEncode_decode
#print axioms finiteSeedGradientEncode_decode
#assert_analysis_axioms finiteSeedGradientEquiv
#print axioms finiteSeedGradientEquiv
#assert_analysis_axioms finiteSeedGradientClock
#print axioms finiteSeedGradientClock
#assert_analysis_axioms finiteSeedGradientClock_seed
#print axioms finiteSeedGradientClock_seed
#assert_analysis_axioms finiteSeedGradientClock_gradient
#print axioms finiteSeedGradientClock_gradient
#assert_analysis_axioms finiteSeedGradientClock_intertwining
#print axioms finiteSeedGradientClock_intertwining
#assert_analysis_axioms finiteSeedGradientOrbit
#print axioms finiteSeedGradientOrbit
#assert_analysis_axioms finiteMaterialOrbit_hasDerivAt
#print axioms finiteMaterialOrbit_hasDerivAt
#assert_analysis_axioms finiteSeedGradientOrbit_hasDerivAt
#print axioms finiteSeedGradientOrbit_hasDerivAt
#assert_analysis_axioms baseTwoCell_materialCutoff
#print axioms baseTwoCell_materialCutoff
#assert_analysis_axioms finiteSeedGradientMaterialPairing
#print axioms finiteSeedGradientMaterialPairing
#assert_analysis_axioms finiteSeedGradientClock_materialPairing_symmetric
#print axioms finiteSeedGradientClock_materialPairing_symmetric
end GeometryOfNumbers.Analysis.BaseTwoCompletion
