import GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev
import Lean
open Lean Elab Command
elab "#assert_finite_clock_height_axioms " id:ident : command => do
  let decl ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo id
  let deps ← collectAxioms decl
  let allowed := #[`propext, `Classical.choice, `Quot.sound]
  for name in deps do
    unless allowed.contains name do
      throwError "Unexpected foundational dependency: {decl} depends on {name}"

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_formal_quotient
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_formal_quotient

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClock
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClock

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialBasis
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialBasis

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClock_basis
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClock_basis

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit_basis
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit_basis

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.clockRate
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.clockRate

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finitePhase_eq_exp
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finitePhase_eq_exp

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.clockJetOrbit
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.clockJetOrbit

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_all_times
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_all_times

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockStrongGenerator
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockStrongGenerator

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockStrongGenerator_pow_apply
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockStrongGenerator_pow_apply

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_eq_generatorPow
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_eq_generatorPow

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_basis
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialClockJet_basis

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalQuarter
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalQuarter

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalQuarter_eq_I_pow
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalQuarter_eq_I_pow

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalRotationCoefficient
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalRotationCoefficient

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalRotationCoefficient_exact
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalRotationCoefficient_exact

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalInitialState
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalInitialState

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.normalizedClockJet
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.normalizedClockJet

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.nativeStateSeries_eq_normalizedClockJet
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.nativeStateSeries_eq_normalizedClockJet

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.nativeStateSeries_quadratures
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.nativeStateSeries_quadratures

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalFiniteHeadCoefficient
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalFiniteHeadCoefficient

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraPeriod
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraPeriod

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraRadiiCount
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraRadiiCount

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalHeadDimension
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalHeadDimension

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeight
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeight

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeights
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeights

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeights_default
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.historicalCameraWeights_default

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockJets_to_head
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteClockJets_to_head

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout_iteratedDerivative
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout_iteratedDerivative

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit_coordinate_hasSum
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteMaterialOrbit_coordinate_hasSum

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout_hasSum
#print axioms GeometryOfNumbers.Analysis.FiniteClockJets.finiteHeadReadout_hasSum

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.headSeries
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.headSeries

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.closedResponseSeries
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.closedResponseSeries

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalPhi
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalPhi

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.externalTail_changes_phi_zero
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.externalTail_changes_phi_zero

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.closedResponseSeries_camera_quotient
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.closedResponseSeries_camera_quotient

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_to_phi_with_external_germs
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_to_phi_with_external_germs

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_determine_phiPrefix
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_determine_phiPrefix

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalPhi_congr_head
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalPhi_congr_head

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_recurrence
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_recurrence

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_isSequence
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_isSequence

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_eq_existing
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_eq_existing

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_formal_logDerivative
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_formal_logDerivative

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_triangular
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteLogMoment_triangular

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledMoment
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledMoment

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScale
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScale

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScaledMoment
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScaledMoment

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScale_pos
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.historicalScale_pos

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledMoment_hankel_entries
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledMoment_hankel_entries

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finitePhiPrefix_determine_Hankel
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finitePhiPrefix_determine_Hankel

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finitePhiPrefix_determine_JacobiSection
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finitePhiPrefix_determine_JacobiSection

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_determine_JacobiSection
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.finiteClockJets_determine_JacobiSection

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_eigenvector_formula
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_eigenvector_formula

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_charpoly
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_charpoly

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeight_positive
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeight_positive

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_one
#print axioms GeometryOfNumbers.Analysis.FiniteClockHeightLedger.scaledFiniteHeightOperator_one

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.ChebyshevState
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.ChebyshevState

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevSeed
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevSeed

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevUpdated
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevUpdated

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevStep
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevStep

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevRun
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.chebyshevRun

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.HistoricalChebyshevAdmissible
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.HistoricalChebyshevAdmissible

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi_isSymm
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi_isSymm

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi_prefix
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevJacobi_prefix

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.finiteClockJets_determine_historicalChebyshev
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.finiteClockJets_determine_historicalChebyshev

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevHeight
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevHeight

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevHeight_charpoly
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.historicalChebyshevHeight_charpoly

#assert_finite_clock_height_axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.finiteClockJets_determine_historicalHeight
#print axioms GeometryOfNumbers.Analysis.FiniteHistoricalChebyshev.finiteClockJets_determine_historicalHeight
