import GeometryOfNumbers.Analysis.FiniteClockKrylovHankel
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.FiniteClockKrylov
#assert_analysis_axioms finiteMaterialClock_pow_apply
#print axioms finiteMaterialClock_pow_apply
#assert_analysis_axioms finiteClockStrongGenerator_pow_eq_clockPow
#print axioms finiteClockStrongGenerator_pow_eq_clockPow
#assert_analysis_axioms finiteMaterialClockJet_eq_krylov
#print axioms finiteMaterialClockJet_eq_krylov
#assert_analysis_axioms normalizedClockJet_eq_krylov
#print axioms normalizedClockJet_eq_krylov
#assert_analysis_axioms finiteClockKrylov_eq_dephasedClockJet
#print axioms finiteClockKrylov_eq_dephasedClockJet
#assert_analysis_axioms finiteClockStrongGenerator_skew_inner
#print axioms finiteClockStrongGenerator_skew_inner
#assert_analysis_axioms finiteClockSpectralMoment
#print axioms finiteClockSpectralMoment
#assert_analysis_axioms finiteClockSpectralMoment_gramRepresentation
#print axioms finiteClockSpectralMoment_gramRepresentation
#assert_analysis_axioms normalizedClockJet_inner_eq_krylov
#print axioms normalizedClockJet_inner_eq_krylov
#assert_analysis_axioms finiteClockHeadCoefficient_eq_krylovReadout
#print axioms finiteClockHeadCoefficient_eq_krylovReadout
#assert_analysis_axioms finiteClockKrylov_inner_complex
#print axioms finiteClockKrylov_inner_complex
#assert_analysis_axioms finiteClockEvenJet_firstColumn
#print axioms finiteClockEvenJet_firstColumn
#assert_analysis_axioms finiteClockOddJet_firstColumn
#print axioms finiteClockOddJet_firstColumn
#assert_analysis_axioms finiteClockRawKrylov_even_odd_pairing
#print axioms finiteClockRawKrylov_even_odd_pairing
#assert_analysis_axioms finiteClockRawKrylov_even_odd_pairing_pos
#print axioms finiteClockRawKrylov_even_odd_pairing_pos
#assert_analysis_axioms finiteClockParityKrylov
#print axioms finiteClockParityKrylov
#assert_analysis_axioms finiteClockParityKrylov_even_eq_normalizedJet
#print axioms finiteClockParityKrylov_even_eq_normalizedJet
#assert_analysis_axioms finiteClockParityKrylov_odd_eq_normalizedJet
#print axioms finiteClockParityKrylov_odd_eq_normalizedJet
#assert_analysis_axioms finiteClockParityKrylov_gramRepresentation
#print axioms finiteClockParityKrylov_gramRepresentation
#assert_analysis_axioms finiteClockEvenSpectralMoment_hankelPair_posSemidef
#print axioms finiteClockEvenSpectralMoment_hankelPair_posSemidef
end GeometryOfNumbers.Analysis.FiniteClockKrylov
