import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms FiniteBaseTwoPhysicalCarrier
#print axioms FiniteBaseTwoPhysicalCarrier
#assert_analysis_axioms finitePhysicalCenterInput
#print axioms finitePhysicalCenterInput
#assert_analysis_axioms finiteOneCellCenterReconstruction
#print axioms finiteOneCellCenterReconstruction
#assert_analysis_axioms finiteOneCellCenterLogGap
#print axioms finiteOneCellCenterLogGap
#assert_analysis_axioms finiteOneCellCenterCoupling
#print axioms finiteOneCellCenterCoupling
#assert_analysis_axioms finitePhysicalCenterSelfCoupling
#print axioms finitePhysicalCenterSelfCoupling
#assert_analysis_axioms finitePhysicalCenterDeltaLeft
#print axioms finitePhysicalCenterDeltaLeft
#assert_analysis_axioms finitePhysicalCenterDeltaRight
#print axioms finitePhysicalCenterDeltaRight
#assert_analysis_axioms finiteOneCellCenterReconstruction_physical
#print axioms finiteOneCellCenterReconstruction_physical
#assert_analysis_axioms finiteOneCellCenterReconstruction_deltaLeft
#print axioms finiteOneCellCenterReconstruction_deltaLeft
#assert_analysis_axioms finiteOneCellCenterReconstruction_deltaRight
#print axioms finiteOneCellCenterReconstruction_deltaRight
#assert_analysis_axioms finitePhysicalCenterSelfCoupling_apply
#print axioms finitePhysicalCenterSelfCoupling_apply
#assert_analysis_axioms finitePhysicalCenterSelfCoupling_deltaLeft
#print axioms finitePhysicalCenterSelfCoupling_deltaLeft
#assert_analysis_axioms finitePhysicalCenterSelfCoupling_deltaRight
#print axioms finitePhysicalCenterSelfCoupling_deltaRight
#assert_analysis_axioms finitePhysicalCenterCoupling_inner_left_right
#print axioms finitePhysicalCenterCoupling_inner_left_right
#assert_analysis_axioms finitePhysicalCenterCoupling_inner_right_image
#print axioms finitePhysicalCenterCoupling_inner_right_image
#assert_analysis_axioms finitePhysicalCenterCoupling_not_symmetric
#print axioms finitePhysicalCenterCoupling_not_symmetric
end GeometryOfNumbers.Analysis.BaseTwoCompletion
