import GeometryOfNumbers.Analysis.FiniteCompletedBoundaryClock
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms finiteBaseTwoLeftEdge
#print axioms finiteBaseTwoLeftEdge
#assert_analysis_axioms finiteBaseTwoRightEdge
#print axioms finiteBaseTwoRightEdge
#assert_analysis_axioms finiteCompletedBoundaryReturn
#print axioms finiteCompletedBoundaryReturn
#assert_analysis_axioms FiniteCompletedBoundaryCarrier
#print axioms FiniteCompletedBoundaryCarrier
#assert_analysis_axioms finiteCompletedBoundaryEmbed
#print axioms finiteCompletedBoundaryEmbed
#assert_analysis_axioms finiteCompletedBoundaryForget
#print axioms finiteCompletedBoundaryForget
#assert_analysis_axioms finiteCompletedBoundaryForget_embed
#print axioms finiteCompletedBoundaryForget_embed
#assert_analysis_axioms finiteCompletedBoundaryGraph
#print axioms finiteCompletedBoundaryGraph
#assert_analysis_axioms finiteCompletedBoundaryGraph_mem_iff
#print axioms finiteCompletedBoundaryGraph_mem_iff
#assert_analysis_axioms finiteCompletedBoundaryClock
#print axioms finiteCompletedBoundaryClock
#assert_analysis_axioms finiteCompletedBoundaryClock_graph_invariant
#print axioms finiteCompletedBoundaryClock_graph_invariant
#assert_analysis_axioms finiteCompletedBoundaryClock_boundary
#print axioms finiteCompletedBoundaryClock_boundary
#assert_analysis_axioms finiteCompletedBoundaryGraphEmbed
#print axioms finiteCompletedBoundaryGraphEmbed
#assert_analysis_axioms finiteCompletedBoundaryClock_intertwining
#print axioms finiteCompletedBoundaryClock_intertwining
#assert_analysis_axioms finiteCompletedBoundaryOrbit
#print axioms finiteCompletedBoundaryOrbit
#assert_analysis_axioms finiteCompletedBoundaryOrbit_hasDerivAt
#print axioms finiteCompletedBoundaryOrbit_hasDerivAt
#assert_analysis_axioms finiteSeedGradientOrbit_historical_gradient
#print axioms finiteSeedGradientOrbit_historical_gradient
#assert_analysis_axioms finiteCompletedBoundaryOrbit_historical_boundary
#print axioms finiteCompletedBoundaryOrbit_historical_boundary
#assert_analysis_axioms finiteCompletedBoundaryOrbit_boundary_hasDerivAt
#print axioms finiteCompletedBoundaryOrbit_boundary_hasDerivAt
#assert_analysis_axioms finiteCompletedBoundaryMaterialBasis
#print axioms finiteCompletedBoundaryMaterialBasis
#assert_analysis_axioms finiteCompletedBoundaryClock_materialBasis
#print axioms finiteCompletedBoundaryClock_materialBasis
#assert_analysis_axioms finiteCompletedBoundaryMaterialBasis_one_two_inner
#print axioms finiteCompletedBoundaryMaterialBasis_one_two_inner
#assert_analysis_axioms finiteCompletedBoundaryClock_not_standard_symmetric
#print axioms finiteCompletedBoundaryClock_not_standard_symmetric
end GeometryOfNumbers.Analysis.BaseTwoCompletion
