import GeometryOfNumbers.Analysis.FiniteCompletedClockGreenIntertwiner
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms ordinaryGradient_isometric_intertwiner_impossible
#print axioms ordinaryGradient_isometric_intertwiner_impossible
#assert_analysis_axioms finiteMaterialGreenDomain
#print axioms finiteMaterialGreenDomain
#assert_analysis_axioms finiteMaterialGreenEmbedding
#print axioms finiteMaterialGreenEmbedding
#assert_analysis_axioms finiteMaterialGreenEmbedding_sum
#print axioms finiteMaterialGreenEmbedding_sum
#assert_analysis_axioms finiteMaterialGreenEmbedding_apply_index
#print axioms finiteMaterialGreenEmbedding_apply_index
#assert_analysis_axioms finiteMaterialGreenEmbedding_inner
#print axioms finiteMaterialGreenEmbedding_inner
#assert_analysis_axioms finiteMaterialGreenEmbedding_norm
#print axioms finiteMaterialGreenEmbedding_norm
#assert_analysis_axioms finiteMaterialGreenEmbedding_injective
#print axioms finiteMaterialGreenEmbedding_injective
#assert_analysis_axioms finiteMaterialGreenEmbedding_clock
#print axioms finiteMaterialGreenEmbedding_clock
#assert_analysis_axioms finiteCompletedEnrichedSource
#print axioms finiteCompletedEnrichedSource
#assert_analysis_axioms finiteCompletedEnrichedSource_fst
#print axioms finiteCompletedEnrichedSource_fst
#assert_analysis_axioms finiteCompletedEnrichedSource_snd
#print axioms finiteCompletedEnrichedSource_snd
#assert_analysis_axioms finiteCompletedEnrichedSource_injective
#print axioms finiteCompletedEnrichedSource_injective
#assert_analysis_axioms finiteCompletedEnrichedSource_ordinary_orbit
#print axioms finiteCompletedEnrichedSource_ordinary_orbit
#assert_analysis_axioms finiteCompletedEnrichedSource_clockGradient_orbit
#print axioms finiteCompletedEnrichedSource_clockGradient_orbit
#assert_analysis_axioms finiteCompletedGraphDecode
#print axioms finiteCompletedGraphDecode
#assert_analysis_axioms finiteCompletedGraphDecode_injective
#print axioms finiteCompletedGraphDecode_injective
#assert_analysis_axioms finiteCompletedGraphDecode_clock
#print axioms finiteCompletedGraphDecode_clock
#assert_analysis_axioms finiteCompletedGreenIntertwiner
#print axioms finiteCompletedGreenIntertwiner
#assert_analysis_axioms finiteCompletedGreenIntertwiner_injective
#print axioms finiteCompletedGreenIntertwiner_injective
#assert_analysis_axioms finiteCompletedGreenIntertwiner_mem_domain
#print axioms finiteCompletedGreenIntertwiner_mem_domain
#assert_analysis_axioms finiteCompletedGreenIntertwiner_clock
#print axioms finiteCompletedGreenIntertwiner_clock
#assert_analysis_axioms finiteCompletedGreenIntertwiner_norm
#print axioms finiteCompletedGreenIntertwiner_norm
#assert_analysis_axioms finiteCompletedGraphDecode_orbit
#print axioms finiteCompletedGraphDecode_orbit
#assert_analysis_axioms finiteCompletedGreenIntertwiner_pairing_symmetric
#print axioms finiteCompletedGreenIntertwiner_pairing_symmetric
#assert_analysis_axioms finiteCompletedGreenIntertwiner_critical_energy
#print axioms finiteCompletedGreenIntertwiner_critical_energy
#assert_analysis_axioms finiteCompletedGreenIntertwiner_critical_energy_tendsto
#print axioms finiteCompletedGreenIntertwiner_critical_energy_tendsto
#assert_analysis_axioms finiteCompletedGreenIntertwiner_critical_no_limit
#print axioms finiteCompletedGreenIntertwiner_critical_no_limit
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis
#print axioms finiteCompletedEnrichedGreenAnalysis
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis_injective
#print axioms finiteCompletedEnrichedGreenAnalysis_injective
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis_clock
#print axioms finiteCompletedEnrichedGreenAnalysis_clock
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis_critical_energy
#print axioms finiteCompletedEnrichedGreenAnalysis_critical_energy
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis_critical_energy_tendsto
#print axioms finiteCompletedEnrichedGreenAnalysis_critical_energy_tendsto
#assert_analysis_axioms finiteCompletedEnrichedGreenAnalysis_critical_no_limit
#print axioms finiteCompletedEnrichedGreenAnalysis_critical_no_limit
end GeometryOfNumbers.Analysis.BaseTwoCompletion
