import GeometryOfNumbers.Analysis.GreenParsevalMaterialEvolution
import Lean
open Lean Elab Command
elab "#assert_green_material_dynamics_axioms " id:ident : command => do
  let decl ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo id
  let deps ← collectAxioms decl
  let allowed := #[`propext, `Classical.choice, `Quot.sound]
  for name in deps do
    unless allowed.contains name do
      throwError "Unexpected foundational dependency: {decl} depends on {name}"

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_eq_native
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_eq_native

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_norm
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_norm

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_zero
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_add
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_add

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_neg
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_neg

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_eq_phaseFactor
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialPhase_eq_phaseFactor

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_apply
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_apply

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_norm
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_norm

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_zero
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_add
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_add

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_neg
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_neg

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_basis
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_basis

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_native_intertwining
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_native_intertwining

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_stronglyContinuous
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_stronglyContinuous

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_stronglyContinuous_at_zero
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_stronglyContinuous_at_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_hasDerivative_zero
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_hasDerivative_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_mem_domain_of_hasDerivative_zero
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_mem_domain_of_hasDerivative_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_differentiableAt_zero_iff
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.greenStateMaterialEvolution_differentiableAt_zero_iff

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.c2GlobalGreenInput_evolution_add
#print axioms GeometryOfNumbers.Analysis.GreenStateMaterialDynamics.c2GlobalGreenInput_evolution_add

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_apply
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_apply

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_zero
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_add
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRangeMaterialEvolution_add

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_apply
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_apply

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRange_inverse_projection_eq_adjoint
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.parsevalRange_inverse_projection_eq_adjoint

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_apply_adjoint
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_apply_adjoint

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_norm
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_norm

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_zero
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_add
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_add

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_neg
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_neg

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_intertwining
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_intertwining

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_eq_self_of_mem_orthogonal
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_eq_self_of_mem_orthogonal

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_stronglyContinuous
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_stronglyContinuous

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_hasDerivative_zero
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_hasDerivative_zero

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_derivative_on_range
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_derivative_on_range

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_c2Source
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_c2Source

#assert_green_material_dynamics_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_c2Source_add
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialDynamics.greenParsevalMaterialEvolution_c2Source_add
