import GeometryOfNumbers.Analysis.GreenParsevalMaterialLogOperator
import Lean

open Lean Elab Command
elab "#assert_green_parseval_log_axioms " id:ident : command => do
  let decl ← liftCoreM <| realizeGlobalConstNoOverloadWithInfo id
  let deps ← collectAxioms decl
  let allowed := #[`propext, `Classical.choice, `Quot.sound]
  for name in deps do
    unless allowed.contains name do
      throwError "Unexpected foundational dependency: {decl} depends on {name}"

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_mem_domain_iff
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_mem_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_apply
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_apply

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_dense_domain
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_dense_domain

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_isSelfAdjoint
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.hilbertPartialProdZero_isSelfAdjoint

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_domain_iff
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_apply
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_apply

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_isSelfAdjoint
#print axioms GeometryOfNumbers.Analysis.UnitaryZeroExtension.selfAdjointZeroExtension_isSelfAdjoint

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis_gram_identity
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis_gram_identity

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis_isometry
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalAnalysis_isometry

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeSubmodule
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeSubmodule

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.ParsevalRange
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.ParsevalRange

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.ParsevalOrthogonal
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.ParsevalOrthogonal

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRange_isClosed
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRange_isClosed

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRange_completeSpace
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRange_completeSpace

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeUnitary
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeUnitary

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeUnitary_apply
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeUnitary_apply

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_domain_iff
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_isSelfAdjoint
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_isSelfAdjoint

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_unitary_mem_domain_iff
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_unitary_mem_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_intertwines
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.parsevalRangeMaterialLogGenerator_intertwines

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalOrthogonalDecomposition
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalOrthogonalDecomposition

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_isSelfAdjoint
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_isSelfAdjoint

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_domain_iff
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_P_mem_domain_iff
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_P_mem_domain_iff

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_intertwining
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_intertwining

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_mem_domain_of_mem_orthogonal
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_mem_domain_of_mem_orthogonal

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_eq_zero_of_mem_orthogonal
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_eq_zero_of_mem_orthogonal

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_transported_basis
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_transported_basis

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_transported_basis_ne_zero
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_transported_basis_ne_zero

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_mem_domain
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_mem_domain

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_intertwining
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_intertwining

#assert_green_parseval_log_axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_domain_iff_log_moment
#print axioms GeometryOfNumbers.Analysis.GreenParsevalMaterialLog.greenParsevalMaterialLogOperator_c2Source_domain_iff_log_moment
