import GeometryOfNumbers.Analysis.PolarizedMomentCoefficients
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms parityJetNumber
#print axioms parityJetNumber
#assert_analysis_axioms realMomentDiagonalCoefficient
#print axioms realMomentDiagonalCoefficient
#assert_analysis_axioms polarizedRealMomentCoefficient
#print axioms polarizedRealMomentCoefficient
#assert_analysis_axioms parityJetNumber_injective
#print axioms parityJetNumber_injective
#assert_analysis_axioms realMomentDiagonalCoefficient_even
#print axioms realMomentDiagonalCoefficient_even
#assert_analysis_axioms realMomentDiagonalCoefficient_odd
#print axioms realMomentDiagonalCoefficient_odd
#assert_analysis_axioms polarizedRealMomentCoefficient_even_even
#print axioms polarizedRealMomentCoefficient_even_even
#assert_analysis_axioms polarizedRealMomentCoefficient_odd_odd
#print axioms polarizedRealMomentCoefficient_odd_odd
#assert_analysis_axioms polarizedRealMomentCoefficient_even_odd
#print axioms polarizedRealMomentCoefficient_even_odd
#assert_analysis_axioms polarizedRealMomentCoefficient_odd_even
#print axioms polarizedRealMomentCoefficient_odd_even
#assert_analysis_axioms polarizedRealMomentCoefficient_eq_parityMomentKernel
#print axioms polarizedRealMomentCoefficient_eq_parityMomentKernel
#assert_analysis_axioms polarizedRealMomentCoefficient_shift
#print axioms polarizedRealMomentCoefficient_shift
end GeometryOfNumbers.Analysis
