import GeometryOfNumbers.Analysis.RealTfvdCenterLegMomentSeam
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms HasC2RealTfvdCenterLegReadout
#print axioms HasC2RealTfvdCenterLegReadout
#assert_analysis_axioms HasBaseTwoCanonicalTfvdCenterLegReadout
#print axioms HasBaseTwoCanonicalTfvdCenterLegReadout
#assert_analysis_axioms c2RealTfvdCenterLegReadout_iff_parityGram
#print axioms c2RealTfvdCenterLegReadout_iff_parityGram
#assert_analysis_axioms c2RealIncidenceJet_inner
#print axioms c2RealIncidenceJet_inner
#assert_analysis_axioms c2RealIncidenceJet_not_parityMomentGram
#print axioms c2RealIncidenceJet_not_parityMomentGram
#assert_analysis_axioms baseTwoRealTfvdCenterLegResidual
#print axioms baseTwoRealTfvdCenterLegResidual
#assert_analysis_axioms baseTwoRealTfvdCenterLegResidual_zero_iff
#print axioms baseTwoRealTfvdCenterLegResidual_zero_iff
#assert_analysis_axioms c2RealIncidenceJet_not_canonicalCenterLegReadout
#print axioms c2RealIncidenceJet_not_canonicalCenterLegReadout
#assert_analysis_axioms c2RealIncidenceJet_residual_not_all_zero
#print axioms c2RealIncidenceJet_residual_not_all_zero
end GeometryOfNumbers.Analysis
