import GeometryOfNumbers.Analysis.Audit

-- The bounded center-role block is not the complete material clock.
namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms separatedCenterBlock_no_injective_finiteClock_intertwiner
#print axioms separatedCenterBlock_no_injective_finiteClock_intertwiner
#assert_analysis_axioms separatedCenterBlock_no_injective_seedGradient_intertwiner
#print axioms separatedCenterBlock_no_injective_seedGradient_intertwiner
#assert_analysis_axioms separatedCenterBlock_exists_excluded_baseTwo_cutoff
#print axioms separatedCenterBlock_exists_excluded_baseTwo_cutoff
#assert_analysis_axioms separatedCenterBlock_not_complete_materialClock_realization
#print axioms separatedCenterBlock_not_complete_materialClock_realization
#assert_analysis_axioms separatedCenterBlock_not_completedBoundaryClock_realization
#print axioms separatedCenterBlock_not_completedBoundaryClock_realization
end GeometryOfNumbers.Analysis.BaseTwoCompletion
