import GeometryOfNumbers.Analysis.Audit

-- Distinct incoming/outgoing center roles; no canonical first column assumed closed.
namespace GeometryOfNumbers.Analysis.BaseTwoCompletion
#assert_analysis_axioms BaseTwoSeparatedCenterHilbert
#print axioms BaseTwoSeparatedCenterHilbert
#assert_analysis_axioms baseTwoSeparatedCenterBlock
#print axioms baseTwoSeparatedCenterBlock
#assert_analysis_axioms baseTwoSeparatedCenterBlock_apply
#print axioms baseTwoSeparatedCenterBlock_apply
#assert_analysis_axioms baseTwoSeparatedCenterBlock_symmetric
#print axioms baseTwoSeparatedCenterBlock_symmetric
#assert_analysis_axioms baseTwoCenterRoleObservation
#print axioms baseTwoCenterRoleObservation
#assert_analysis_axioms baseTwoCenterRoleObservation_apply
#print axioms baseTwoCenterRoleObservation_apply
#assert_analysis_axioms baseTwoSeparatedCenterBlock_physical
#print axioms baseTwoSeparatedCenterBlock_physical
#assert_analysis_axioms baseTwoCenterRoleObservation_energy
#print axioms baseTwoCenterRoleObservation_energy
#assert_analysis_axioms baseTwoSeparatedCenterKrylov_inner_add
#print axioms baseTwoSeparatedCenterKrylov_inner_add
#assert_analysis_axioms baseTwoSeparatedCenter_firstColumn_implies_evenKernel
#print axioms baseTwoSeparatedCenter_firstColumn_implies_evenKernel
end GeometryOfNumbers.Analysis.BaseTwoCompletion
