import GeometryOfNumbers.Analysis.SymmetricKrylovHankel
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms symmetricKrylov_inner_add
#print axioms symmetricKrylov_inner_add
#assert_analysis_axioms krylovSpectralMoment
#print axioms krylovSpectralMoment
#assert_analysis_axioms krylovSpectralMoment_gramRepresentation
#print axioms krylovSpectralMoment_gramRepresentation
#assert_analysis_axioms firstColumn_of_symmetric_implies_hankelGram
#print axioms firstColumn_of_symmetric_implies_hankelGram
#assert_analysis_axioms krylovSpectralMoment_hankel_posSemidef
#print axioms krylovSpectralMoment_hankel_posSemidef
#assert_analysis_axioms krylovSpectralMoment_hankel_posDef
#print axioms krylovSpectralMoment_hankel_posDef
#assert_analysis_axioms krylovSpectralMoment_eq_of_logDerivativeRelations
#print axioms krylovSpectralMoment_eq_of_logDerivativeRelations
end GeometryOfNumbers.Analysis
