import GeometryOfNumbers.Analysis.VerticalIncidenceGramObstruction
import GeometryOfNumbers.Analysis.Audit

namespace GeometryOfNumbers.Analysis
#assert_analysis_axioms c2TfvdReconstructedBranchState
#print axioms c2TfvdReconstructedBranchState
#assert_analysis_axioms c2TfvdReconstructedBranchState_eq
#print axioms c2TfvdReconstructedBranchState_eq
#assert_analysis_axioms c2TfvdReconstructedBranchState_inner
#print axioms c2TfvdReconstructedBranchState_inner
#assert_analysis_axioms c2TfvdReconstructedIncidence_not_parityMomentGram
#print axioms c2TfvdReconstructedIncidence_not_parityMomentGram
#assert_analysis_axioms c2IsometricIncidenceSynthesis_inner
#print axioms c2IsometricIncidenceSynthesis_inner
#assert_analysis_axioms c2IsometricIncidenceSynthesis_linearIndependent
#print axioms c2IsometricIncidenceSynthesis_linearIndependent
#assert_analysis_axioms c2IsometricIncidenceSynthesis_gramPair_posDef
#print axioms c2IsometricIncidenceSynthesis_gramPair_posDef
#assert_analysis_axioms c2IsometricIncidenceSynthesis_hankel_three_ne_gram
#print axioms c2IsometricIncidenceSynthesis_hankel_three_ne_gram
#assert_analysis_axioms c2IsometricIncidenceSynthesis_not_parityMomentGram
#print axioms c2IsometricIncidenceSynthesis_not_parityMomentGram
#assert_analysis_axioms c2IsometricIncidenceSynthesis_not_canonicalParityMomentGram
#print axioms c2IsometricIncidenceSynthesis_not_canonicalParityMomentGram
end GeometryOfNumbers.Analysis
